// GENERATED FROM A ONE-OFF SOURCE, THEN OWNED HERE. Edit this file
// directly; there is no generator to re-run. 繁體 was produced with
// OpenCC (`opencc -c s2twp`) and then corrected where its Taiwan
// phrasing differs from what this app already says on screen:
//   插圖 → 插畫
//   重新檢視導覽 → 重新查看導覽
//   傳送測試通知 → 發送測試通知
//   彙總 → 匯總
//   字型 → 字體
//   母音 → 元音
//   映象 → 鏡像
//   重灌 → 重新安裝
//   型別 → 類型
//   位址列 → 網址列
//   新增到主螢幕 → 加入主畫面
//   畫素 → 像素
// Writing new 繁體 by the same route? Apply the same list.
//
// ignore_for_file: lines_longer_than_80_chars

/// Everything the Help page says about Yahweh's Sword — see `help_catalog.dart`
/// for the model and the rules, and `test/help_catalog_test.dart` for
/// what keeps it honest (every path key exists, every example key
/// exists, every destination opens, the searches people actually type
/// find something).
///
/// Written against the code on 2026-09-18, not against the README,
/// which is allowed to drift; a help page must not inherit that. Where a
/// sentence names a menu, it names it with the menu's own label.
library;

import 'package:yahwehs_sword/utils/help_catalog.dart';

const List<HelpTopic> kHelpTopics = [
  HelpTopic(
    id: 'overview',
    section: HelpSection.start,
    title: HelpText(
      '雅伟之剑是什么',
      '雅偉之劍是什麼',
      'What Yahweh\'s Sword is',
    ),
    body: HelpText(
      '雅伟之剑是一个研经工作台，照 BibleWorks 的思路设计：搜索、经文和分析同时摆在一个屏幕上，不用来回切换页面。\n\n• 左边是「搜索窗口」：命令行和搜索结果。\n• 中间是经文：并排对照、经典阅读模式或双栏对读。\n• 右边是「分析窗口」：你选中哪节经文、指到哪个原文词，它就讲哪个。\n\n最上面是菜单栏（文件、视图、搜索、工具、资源、帮助）和工具栏，最下面是状态栏，显示当前位置、版本，以及鼠标所指的原文词。',
      '雅偉之劍是一個研經工作臺，照 BibleWorks 的思路設計：搜尋、經文和分析同時擺在一個螢幕上，不用來回切換頁面。\n\n• 左邊是「搜尋視窗」：命令列和搜尋結果。\n• 中間是經文：並排對照、經典閱讀模式或雙欄對讀。\n• 右邊是「分析視窗」：你選中哪節經文、指到哪個原文詞，它就講哪個。\n\n最上面是選單欄（檔案、檢視、搜尋、工具、資源、幫助）和工具欄，最下面是狀態列，顯示當前位置、版本，以及滑鼠所指的原文詞。',
      'Yahweh\'s Sword is a Bible-study workbench in the spirit of BibleWorks: search, text and analysis sit on one screen together, so you never switch pages to look something up.\n\n• Left: the Search window — the command line and its results.\n• Centre: the text — Parallel, Classic Reader or Split.\n• Right: the Analysis window — it explains whichever verse you selected or word you are pointing at.\n\nAcross the top are the menu bar (File, View, Search, Tools, Resources, Help) and the toolbar; along the bottom the status bar shows where you are, the version, and the original-language word under the pointer.',
    ),
    keywords: [
      'workbench',
      'BibleWorks',
      '工作台',
      '三栏',
      'panes',
      'layout',
      '布局',
      '界面',
      'interface',
      '介绍',
      'introduction',
      'status bar',
      '状态栏',
      '菜单',
      'menu',
    ],
  ),
  HelpTopic(
    id: 'screen-size',
    section: HelpSection.start,
    title: HelpText(
      '需要多大的屏幕',
      '需要多大的螢幕',
      'How much screen it needs',
    ),
    body: HelpText(
      '三栏并排至少需要 992 像素宽：电脑、横放的 iPad、较大的 Android 平板都够。\n\n• 竖着拿 iPad 时，如果横过来就放得下，会提示你把设备转过来。\n• 手机横竖都放不下三栏，会建议改用姊妹 app「雅伟之言」（yahwehword.com），那是专为手机做的读经 app，笔记和高亮的用法一样。',
      '三欄並排至少需要 992 像素寬：電腦、橫放的 iPad、較大的 Android 平板都夠。\n\n• 豎著拿 iPad 時，如果橫過來就放得下，會提示你把裝置轉過來。\n• 手機橫豎都放不下三欄，會建議改用姊妹 app「雅偉之言」（yahwehword.com），那是專為手機做的讀經 app，筆記和高亮的用法一樣。',
      'Three panes side by side need at least 992 pixels: a computer, an iPad held landscape and larger Android tablets all qualify.\n\n• Holding an iPad in portrait, you are asked to turn it round if landscape would fit.\n• A phone cannot fit three panes either way, so you are pointed to the sister app, Yahweh\'s Words (yahwehword.com), which is built for phones.',
    ),
    keywords: [
      'phone',
      '手机',
      'iPhone',
      'rotate',
      '旋转',
      '横屏',
      '竖屏',
      '太小',
      'too small',
      '992',
      '宽度',
      'width',
      '雅伟之言',
      'Yahweh\'s Words',
      'foldable',
      '折叠屏',
    ],
    notes: {
      HelpPlatform.ios: HelpText(
        'iPad 横放即可。开了「分屏浏览」让窗口变窄时，可能会看到转向提示。',
        'iPad 橫放即可。開了「分屏瀏覽」讓視窗變窄時，可能會看到轉向提示。',
        'Hold the iPad landscape. Split View multitasking narrows the window and may bring up the rotate notice.',
      ),
      HelpPlatform.android: HelpText(
        '折叠屏展开后宽度仍不够三栏，这是有意的：三栏挤在那个宽度里字会小到看不清。',
        '摺疊屏展開後寬度仍不夠三欄，這是有意的：三欄擠在那個寬度裡字會小到看不清。',
        'An unfolded foldable is still too narrow for three panes — on purpose: squeezed to that width the text becomes unreadable.',
      ),
    },
  ),
  HelpTopic(
    id: 'panes',
    section: HelpSection.start,
    title: HelpText(
      '打开、关闭和调整三栏',
      '開啟、關閉和調整三欄',
      'Opening, closing and resizing the panes',
    ),
    body: HelpText(
      '「视图」菜单里的「搜索窗口」「分析窗口」分别开关左右两栏，打勾表示正在显示。\n\n栏与栏之间的分隔条可以拖动来调宽窄。屏幕不够宽时先关掉分析窗口，中间的经文就会分到更多空间。',
      '「檢視」選單裡的「搜尋視窗」「分析視窗」分別開關左右兩欄，打勾表示正在顯示。\n\n欄與欄之間的分隔條可以拖動來調寬窄。螢幕不夠寬時先關掉分析視窗，中間的經文就會分到更多空間。',
      'View › Search window and View › Analysis window switch the left and right panes on and off; a tick means it is showing.\n\nDrag the divider between two panes to resize them. When the screen is tight, close the Analysis window first and the text gets the room.',
    ),
    path: ['menuView', 'menuSearchWindow'],
    keywords: [
      '隐藏',
      'hide',
      'show',
      '显示',
      'resize',
      '拖动',
      'drag',
      'divider',
      '分隔',
      '宽度',
      'width',
      '侧栏',
      'sidebar',
      '关闭',
      'close',
    ],
    notes: {
      HelpPlatform.ios: HelpText(
        '用手指按住分隔条拖动。',
        '用手指按住分隔條拖動。',
        'Drag the divider with a finger.',
      ),
      HelpPlatform.android: HelpText(
        '用手指按住分隔条拖动。',
        '用手指按住分隔條拖動。',
        'Drag the divider with a finger.',
      ),
    },
  ),
  HelpTopic(
    id: 'help',
    section: HelpSection.start,
    title: HelpText(
      '怎么用这份说明',
      '怎麼用這份說明',
      'Using this help',
    ),
    body: HelpText(
      '打开这里有三种方法：「帮助」菜单 ›「使用说明与快捷键」、键盘上的 F1，或者在经文区按 ?。\n\n• 顶上的搜索框可以用中文（简繁都行）、英文或按键名搜，例如「投影」「copy」「F4」。\n• 平台选项默认是你正在用的设备；换一个平台就能看到同一功能在那里怎么用、用哪些键。\n• 标着「带我去」的条目，点一下直接打开那个功能。',
      '開啟這裡有三種方法：「幫助」選單 ›「使用說明與快捷鍵」、鍵盤上的 F1，或者在經文區按 ?。\n\n• 頂上的搜尋框可以用中文（簡繁都行）、英文或按鍵名搜，例如「投影」「copy」「F4」。\n• 平臺選項預設是你正在用的裝置；換一個平臺就能看到同一功能在那裡怎麼用、用哪些鍵。\n• 標著「帶我去」的條目，點一下直接開啟那個功能。',
      'Three ways in: Help › Help & shortcuts, F1 on the keyboard, or ? while in the text.\n\n• The search box takes Chinese (simplified or traditional), English or a key name — "projection", "复制", "F4".\n• The platform choice starts on the device you are using; switch it to see how the same feature works, and which keys it uses, somewhere else.\n• Entries marked "Take me there" open the feature directly.',
    ),
    path: ['menuHelp', 'helpTitle'],
    keywords: [
      'help',
      '帮助',
      '说明',
      'F1',
      '搜索功能',
      '找不到',
      'where',
      '在哪',
      'manual',
      '手册',
      'guide',
      '教程',
      'tutorial',
    ],
  ),
  HelpTopic(
    id: 'go-to',
    section: HelpSection.reading,
    title: HelpText(
      '跳到某卷、某章、某节',
      '跳到某卷、某章、某節',
      'Going to a book, chapter or verse',
    ),
    body: HelpText(
      '最快的是命令行（按 F2）：直接打「约 3:16」「John 3:16」「罗 12:1-2」再按回车。\n\n• 只打「3:16」：本卷第 3 章 16 节。\n• 只打「17」：本章第 17 节。\n\n也可以用「资源」›「跳转书卷…」从列表里挑卷和章。上一章、下一章：工具栏上的左右箭头，或键盘上的 [ 和 ]。',
      '最快的是命令列（按 F2）：直接打「約 3:16」「John 3:16」「羅 12:1-2」再按回車。\n\n• 只打「3:16」：本卷第 3 章 16 節。\n• 只打「17」：本章第 17 節。\n\n也可以用「資源」›「跳轉書卷…」從列表裡挑卷和章。上一章、下一章：工具欄上的左右箭頭，或鍵盤上的 [ 和 ]。',
      'Fastest is the command line (F2): type "John 3:16", "约 3:16" or "Rom 12:1-2" and press Enter.\n\n• "3:16" alone: chapter 3 verse 16 of the current book.\n• "17" alone: verse 17 of the current chapter.\n\nOr Resources › Go to book… and pick from the list. Previous and next chapter: the arrows on the toolbar, or [ and ] on the keyboard.',
    ),
    path: ['menuResources', 'books'],
    keywords: [
      '跳转',
      'jump',
      'goto',
      'navigate',
      '导航',
      '书卷',
      'book',
      'chapter',
      'verse',
      '章',
      '节',
      'reference',
      '出处',
      '上一章',
      '下一章',
      'previous',
      'next',
      '翻页',
      'page',
    ],
    notes: {
      HelpPlatform.ios: HelpText(
        '在经典阅读模式里，左右滑动经文也可以翻章。',
        '在經典閱讀模式裡，左右滑動經文也可以翻章。',
        'In Classic Reader, swiping the text sideways also turns the chapter.',
      ),
      HelpPlatform.android: HelpText(
        '在经典阅读模式里，左右滑动经文也可以翻章。',
        '在經典閱讀模式裡，左右滑動經文也可以翻章。',
        'In Classic Reader, swiping the text sideways also turns the chapter.',
      ),
    },
    open: HelpDestination.books,
  ),
  HelpTopic(
    id: 'centre-modes',
    section: HelpSection.reading,
    title: HelpText(
      '中间栏的三种排法',
      '中間欄的三種排法',
      'Three ways to lay out the centre',
    ),
    body: HelpText(
      '在「视图」菜单里选：\n\n• 并排对照：几个译本逐节对齐，适合比较。原文词可以指向或点击，右边的分析窗口跟着讲。\n• 经典阅读模式：一个译本整章连读，点经节可以选中它。\n• 双栏对读：两个译本各占一栏并排。中间不够宽时这一项是灰的，旁边写着原因——关掉分析窗口通常就够了。',
      '在「檢視」選單裡選：\n\n• 並排對照：幾個譯本逐節對齊，適合比較。原文詞可以指向或點選，右邊的分析視窗跟著講。\n• 經典閱讀模式：一個譯本整章連讀，點經節可以選中它。\n• 雙欄對讀：兩個譯本各佔一欄並排。中間不夠寬時這一項是灰的，旁邊寫著原因——關掉分析視窗通常就夠了。',
      'Choose on the View menu:\n\n• Parallel: several versions aligned verse by verse, for comparing. Original-language words respond to pointing and tapping, and the Analysis window follows.\n• Classic Reader: one version, the whole chapter as continuous text; tap a verse to select it.\n• Split: two versions in two columns. Greyed out, with the reason beside it, when the centre is too narrow — closing the Analysis window is usually enough.',
    ),
    path: ['menuView', 'parallelBrowse'],
    keywords: [
      'browse',
      'parallel',
      '平行',
      '对照',
      '并排',
      'split',
      '分屏',
      '双栏',
      'reader',
      '阅读模式',
      'classic',
      'layout',
      '排版',
    ],
  ),
  HelpTopic(
    id: 'versions',
    section: HelpSection.reading,
    title: HelpText(
      '选择对照的译本',
      '選擇對照的譯本',
      'Choosing versions to compare',
    ),
    body: HelpText(
      '「视图」›「选择版本…」勾选要在并排对照里出现的译本。\n\n命令行更快：\n• d kjv 加入 KJV；d -kjv 移除；d c 清空（只留搜索用的版本）；d english 加入所有英文译本\n• p kjv bsb 一次换成这几个，并按你打的顺序排列——勾选框做不到排序\n• 单独打一个版本缩写（例如 kjv）再按回车，就把阅读版本换成它',
      '「檢視」›「選擇版本…」勾選要在並排對照裡出現的譯本。\n\n命令列更快：\n• d kjv 加入 KJV；d -kjv 移除；d c 清空（只留搜尋用的版本）；d english 加入所有英文譯本\n• p kjv bsb 一次換成這幾個，並按你打的順序排列——勾選框做不到排序\n• 單獨打一個版本縮寫（例如 kjv）再按回車，就把閱讀版本換成它',
      'View › Choose versions… ticks which versions appear in Parallel.\n\nThe command line is quicker:\n• d kjv adds the KJV; d -kjv removes it; d c clears back to the search version; d english adds every English edition\n• p kjv bsb replaces the set with exactly these, in the order typed — something a checklist cannot do\n• a version abbreviation on its own (kjv) plus Enter switches the reading version to it',
    ),
    path: ['menuView', 'parallelPickVersions'],
    keywords: [
      'version',
      'translation',
      '译本',
      '版本',
      '和合本',
      'KJV',
      'BSB',
      'NASB',
      'CUV',
      'compare',
      '对照',
      'add',
      'remove',
      '切换版本',
      'switch',
      'd',
      'p',
    ],
    open: HelpDestination.chooseVersions,
  ),
  HelpTopic(
    id: 'diff',
    section: HelpSection.reading,
    title: HelpText(
      '标示版本差异',
      '標示版本差異',
      'Highlighting where versions differ',
    ),
    body: HelpText(
      '「视图」›「标示版本差异」会把同一语言的几个译本之间措辞不同的地方标出来。\n\n前提是并排对照里至少有两个同语言的译本（两个中文或两个英文）。不满足时这一项是灰的，并写明还缺什么。',
      '「檢視」›「標示版本差異」會把同一語言的幾個譯本之間措辭不同的地方標出來。\n\n前提是並排對照裡至少有兩個同語言的譯本（兩個中文或兩個英文）。不滿足時這一項是灰的，並寫明還缺什麼。',
      'View › Highlight version differences marks where editions of the same language word things differently.\n\nIt needs at least two editions of one language in Parallel (two Chinese or two English). Otherwise the item is greyed out and says what is missing.',
    ),
    path: ['menuView', 'browseDiffHighlight'],
    keywords: [
      'diff',
      'difference',
      '差异',
      '不同',
      'compare',
      '比较',
      'variant',
    ],
  ),
  HelpTopic(
    id: 'second-column',
    section: HelpSection.reading,
    title: HelpText(
      '第二栏：跟随还是独立翻页',
      '第二欄：跟隨還是獨立翻頁',
      'The second column: following or independent',
    ),
    body: HelpText(
      '双栏对读时，第二栏默认跟着第一栏翻页。\n\n「视图」›「第二栏：独立翻页」打勾后，它就停在自己的位置，两边可以看不同的章节；取消勾选会立刻跳回和第一栏同步。',
      '雙欄對讀時，第二欄預設跟著第一欄翻頁。\n\n「檢視」›「第二欄：獨立翻頁」打勾後，它就停在自己的位置，兩邊可以看不同的章節；取消勾選會立刻跳回和第一欄同步。',
      'In Split, the second column follows the first by default.\n\nTick View › Second column: independent and it stays where it is, so the two sides can show different chapters; untick it and it jumps back into step.',
    ),
    path: ['menuView', 'secondColumnIndependent'],
    keywords: [
      'split',
      '双栏',
      '第二栏',
      'second column',
      'sync',
      '同步',
      'follow',
      '跟随',
      'independent',
      '独立',
    ],
  ),
  HelpTopic(
    id: 'words',
    section: HelpSection.reading,
    title: HelpText(
      '指向或点击原文词',
      '指向或點選原文詞',
      'Pointing at or clicking a word',
    ),
    body: HelpText(
      '在并排对照里，鼠标指到一个原文词，分析窗口和底部状态栏就显示它；同一个 Strong 编号的其他词会一起亮起来。\n\n点一下这个词就把它「锁定」：鼠标移开，分析窗口也不再跟着变，上方会出现一条锁定栏。锁定在换章之后仍然保留。\n\n取消锁定有四种方法：再点一次同一个词、点锁定栏上的按钮、按 Esc、或者点经文里别的地方。',
      '在並排對照裡，滑鼠指到一個原文詞，分析視窗和底部狀態列就顯示它；同一個 Strong 編號的其他詞會一起亮起來。\n\n點一下這個詞就把它「鎖定」：滑鼠移開，分析視窗也不再跟著變，上方會出現一條鎖定欄。鎖定在換章之後仍然保留。\n\n取消鎖定有四種方法：再點一次同一個詞、點鎖定欄上的按鈕、按 Esc、或者點經文裡別的地方。',
      'In Parallel, pointing at an original-language word shows it in the Analysis window and the status bar, and every other word with the same Strong\'s number lights up.\n\nClick the word to pin it: the Analysis window stops following the pointer and a pin bar appears above it. A pin survives a chapter change.\n\nFour ways to unpin: click the same word again, the button on the pin bar, Esc, or click anywhere else in the text.',
    ),
    keywords: [
      'hover',
      '悬停',
      '指向',
      'pin',
      '锁定',
      '钉住',
      'unpin',
      'Strong',
      '原文',
      'word',
      'lemma',
      'Esc',
      'status bar',
      '状态栏',
      'mouse',
      '鼠标',
    ],
    notes: {
      HelpPlatform.ios: HelpText(
        '触屏没有「指向」，所以点一下就是锁定，并自动切到能显示它的分页；再点一次取消。',
        '觸屏沒有「指向」，所以點一下就是鎖定，並自動切到能顯示它的分頁；再點一次取消。',
        'A touch screen has no pointing, so a tap pins the word and brings forward a tab that shows it; tap again to release.',
      ),
      HelpPlatform.android: HelpText(
        '触屏没有「指向」，所以点一下就是锁定，并自动切到能显示它的分页；再点一次取消。',
        '觸屏沒有「指向」，所以點一下就是鎖定，並自動切到能顯示它的分頁；再點一次取消。',
        'A touch screen has no pointing, so a tap pins the word and brings forward a tab that shows it; tap again to release.',
      ),
    },
  ),
  HelpTopic(
    id: 'select-verses',
    section: HelpSection.reading,
    title: HelpText(
      '选中经文后能做什么',
      '選中經文後能做什麼',
      'What you can do with selected verses',
    ),
    body: HelpText(
      '在经典阅读模式里点一节经文就选中它，可以接着点选多节。选中后出现一排操作：\n\n• 原文逐字：逐字对照原文\n• 相互参照：串珠经文\n• 笔记、书签、高亮\n• 投影：把这几节放到投影页\n• 复制、分享\n\n再点一次已选的经节，或点「清除选择」，取消选择。',
      '在經典閱讀模式裡點一節經文就選中它，可以接著點選多節。選中後出現一排操作：\n\n• 原文逐字：逐字對照原文\n• 相互參照：串珠經文\n• 筆記、書籤、高亮\n• 投影：把這幾節放到投影頁\n• 複製、分享\n\n再點一次已選的經節，或點「清除選擇」，取消選擇。',
      'In Classic Reader, tap a verse to select it; keep tapping to select several. A row of actions appears:\n\n• Original: word-by-word interlinear\n• Cross-references\n• Note, bookmark, highlight\n• Project: put these verses on the projection page\n• Copy, share\n\nTap a selected verse again, or Clear selection, to deselect.',
    ),
    keywords: [
      'select',
      '选中',
      '选择',
      '多选',
      'multi',
      'copy',
      '复制',
      'share',
      '分享',
      'highlight',
      '高亮',
      'note',
      '笔记',
      'bookmark',
      '书签',
      'cross reference',
      '串珠',
      '互参',
      'project',
      '投影',
      'interlinear',
      '逐字',
    ],
  ),
  HelpTopic(
    id: 'appearance',
    section: HelpSection.reading,
    title: HelpText(
      '深色模式、字体与字号',
      '深色模式、字體與字號',
      'Dark mode, fonts and text size',
    ),
    body: HelpText(
      '「视图」›「深色模式」一键切换。\n\n其余外观在「文件」›「设置」：字号、菜单大小、行距、字体、主题色、浅色/深色/跟随系统，以及护眼纸质背景。改动即时生效，设置页里有预览。',
      '「檢視」›「深色模式」一鍵切換。\n\n其餘外觀在「檔案」›「設定」：字號、選單大小、行距、字體、主題色、淺色/深色/跟隨系統，以及護眼紙質背景。改動即時生效，設定頁裡有預覽。',
      'View › Dark mode switches in one click.\n\nEverything else is in File › Settings: text size, menu size, line spacing, font, theme colour, light/dark/system, and the paper-tone reading background. Changes apply at once, with a preview.',
    ),
    path: ['menuFile', 'settings'],
    keywords: [
      'dark',
      '夜间',
      '深色',
      '暗色',
      'theme',
      '主题',
      'font',
      '字体',
      'size',
      '字号',
      '大小',
      'zoom',
      '放大',
      '缩小',
      'line spacing',
      '行距',
      'paper',
      '护眼',
      'color',
      'colour',
      '颜色',
      'light',
      '浅色',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'command-line',
    section: HelpSection.search,
    title: HelpText(
      '命令行：一个框做所有事',
      '命令列：一個框做所有事',
      'The command line does everything',
    ),
    body: HelpText(
      '搜索窗口顶上的命令行是整个工作台的键盘入口。按 F2（或「搜索」›「命令行」）把光标放进去，然后：\n\n• 打经文出处就跳过去：约 3:16、John 3:16\n• 打版本缩写就换阅读版本：kjv、bsb\n• 打 G26、H430 这样的 Strong 编号，就找这个原文词出现在哪里\n• 打其他文字就是搜索；前面加 . / \' 等符号可以精确控制（见「文字搜索的写法」）\n• 单个字母加空格开头的是命令：d、p、l（见「命令」）\n\n↑ ↓ 调出以前输入过的内容，Esc 清空。输入框下面那排按钮会插入运算符；⌥ 按钮打开「搭一条查询」，一步步帮你拼出查询；? 按钮打开语法卡，点卡上任何一行就把例子填进命令行（不会自动执行，方便你先改）。',
      '搜尋視窗頂上的命令列是整個工作臺的鍵盤入口。按 F2（或「搜尋」›「命令列」）把游標放進去，然後：\n\n• 打經文出處就跳過去：約 3:16、John 3:16\n• 打版本縮寫就換閱讀版本：kjv、bsb\n• 打 G26、H430 這樣的 Strong 編號，就找這個原文詞出現在哪裡\n• 打其他文字就是搜尋；前面加 . / \' 等符號可以精確控制（見「文字搜尋的寫法」）\n• 單個字母加空格開頭的是命令：d、p、l（見「命令」）\n\n↑ ↓ 調出以前輸入過的內容，Esc 清空。輸入框下面那排按鈕會插入運算子；⌥ 按鈕開啟「搭一條查詢」，一步步幫你拼出查詢；? 按鈕開啟語法卡，點卡上任何一行就把例子填進命令列（不會自動執行，方便你先改）。',
      'The command line at the top of the Search window is the keyboard way into the whole workbench. Press F2 (or Search › Command line) to put the caret there, then:\n\n• type a reference to go there: John 3:16, 约 3:16\n• type a version abbreviation to switch the reading version: kjv, bsb\n• type a Strong\'s number such as G26 or H430 to find where that word occurs\n• type anything else to search; a leading . / \' and so on controls how (see "Writing a text search")\n• a single letter and a space starts a command: d, p, l (see "Commands")\n\n↑ ↓ recall earlier lines, Esc clears. The buttons under the box insert operators; ⌥ opens Build a search, which writes a query for you step by step; ? opens the syntax card — tap any line on it to put that example on the command line, unrun, so you can edit it first.',
    ),
    path: ['search', 'menuFocusCommandLine'],
    keywords: [
      'command line',
      '命令行',
      '命令列',
      'search box',
      '搜索框',
      'F2',
      'query',
      '查询',
      'Strong',
      '编号',
      'BibleWorks',
      'builder',
      '生成器',
      '搭一条查询',
      'Build a search',
      'syntax',
      '语法',
      'history',
      '历史',
      '↑',
    ],
    open: HelpDestination.commandLine,
  ),
  HelpTopic(
    id: 'text-search',
    section: HelpSection.search,
    title: HelpText(
      '文字搜索的写法',
      '文字搜尋的寫法',
      'Writing a text search',
    ),
    body: HelpText(
      '第一个字符决定搜索的类型。在这里点一行会复制它的查询；在命令行的 ? 卡上点同一行，则直接填进命令行。\n\n中文按字匹配，英文按词匹配：「.爱 神」是同一节里既有「爱」也有「神」；「.爱神」是连在一起的「爱神」。',
      '第一個字元決定搜尋的類型。在這裡點一行會複製它的查詢；在命令列的 ? 卡上點同一行，則直接填進命令列。\n\n中文按字匹配，英文按詞匹配：「.愛 神」是同一節裡既有「愛」也有「神」；「.愛神」是連在一起的「愛神」。',
      'The first character decides what kind of search it is. Tap a line here to copy its query; tap the same line on the command line\'s ? card to put it straight on the command line.\n\nChinese matches by character, English by word: ".爱 神" is a verse holding both 爱 and 神; ".爱神" is the two together.',
    ),
    examples: [
      'cmdSyntaxAnd',
      'cmdSyntaxOr',
      'cmdSyntaxPhrase',
      'cmdSyntaxNot',
      'cmdSyntaxWild',
      'cmdSyntaxGap',
      'cmdSyntaxContext',
      'cmdSyntaxCompound',
      'cmdSyntaxCrossVersion',
      'cmdSyntaxRegex',
    ],
    keywords: [
      'AND',
      'OR',
      'NOT',
      'phrase',
      '短语',
      '词组',
      'wildcard',
      '通配符',
      'regex',
      '正则',
      'proximity',
      '相隔',
      'context',
      'compound',
      '组合',
      'exclude',
      '排除',
      'operator',
      '运算符',
      '符号',
    ],
  ),
  HelpTopic(
    id: 'strongs-search',
    section: HelpSection.search,
    title: HelpText(
      '按原文编号搜索',
      '按原文編號搜尋',
      'Searching by Strong\'s number',
    ),
    body: HelpText(
      '原文编号（G 是希腊文，H 是希伯来文）可以用 AND、OR、NOT、NEAR、BEFORE 组合。\n\n编号从哪里来？在分析窗口的「原文研读」里点任何一个词都看得到；或者打开「工具」›「词汇表」看本章的全部原文词。',
      '原文編號（G 是希臘文，H 是希伯來文）可以用 AND、OR、NOT、NEAR、BEFORE 組合。\n\n編號從哪裡來？在分析視窗的「原文研讀」裡點任何一個詞都看得到；或者開啟「工具」›「詞彙表」看本章的全部原文詞。',
      'Strong\'s numbers (G for Greek, H for Hebrew) combine with AND, OR, NOT, NEAR and BEFORE.\n\nWhere do the numbers come from? Any word in the Analysis window\'s Word Study shows its number; or open Tools › Word List for every word in the chapter.',
    ),
    path: ['menuTools', 'wordListTitle'],
    examples: [
      'cmdSyntaxStrongsBool',
      'cmdSyntaxStrongsNear',
      'cmdSyntaxStrongsBefore',
      'cmdSyntaxStrongsWild',
    ],
    keywords: [
      'Strong',
      'Strong\'s',
      'G',
      'H',
      '希腊文',
      '希伯来文',
      'Greek',
      'Hebrew',
      'lemma',
      '原文',
      'NEAR',
      'BEFORE',
      '编号',
      'number',
      'concordance',
      '汇编',
    ],
  ),
  HelpTopic(
    id: 'verbs',
    section: HelpSection.search,
    title: HelpText(
      '命令：d、p、l 和数字',
      '命令：d、p、l 和數字',
      'Commands: d, p, l and bare numbers',
    ),
    body: HelpText(
      '• d nas 把 NASB 加进并排对照；d -nas 移除；d c 清空；d english 加入所有英文译本\n• p a b c 把并排对照换成 a、b、c，按这个顺序；单独一个 p 切到并排对照\n• l 创 只在创世记里搜；l nt 只搜新约；l 太 5-7 只搜马太福音 5 到 7 章；单独一个 l 取消限制\n• 3:16 跳到本卷 3 章 16 节；17 跳到本章第 17 节\n\nl 只能按卷和章限定；要按任意一组经节限定，用分析窗口的「经文列表」。',
      '• d nas 把 NASB 加進並排對照；d -nas 移除；d c 清空；d english 加入所有英文譯本\n• p a b c 把並排對照換成 a、b、c，按這個順序；單獨一個 p 切到並排對照\n• l 創 只在創世記裡搜；l nt 只搜新約；l 太 5-7 只搜馬太福音 5 到 7 章；單獨一個 l 取消限制\n• 3:16 跳到本卷 3 章 16 節；17 跳到本章第 17 節\n\nl 只能按卷和章限定；要按任意一組經節限定，用分析視窗的「經文列表」。',
      '• d nas adds the NASB to Parallel; d -nas removes it; d c clears; d english adds every English edition\n• p a b c replaces Parallel with a, b, c in that order; p alone switches to Parallel\n• l gen limits searches to Genesis; l nt to the New Testament; l matt 5-7 to Matthew 5–7; l alone lifts the limit\n• 3:16 goes to chapter 3 verse 16 of this book; 17 to verse 17 of this chapter\n\nl limits by book and chapter only; to limit to any set of verses, use a list on the Analysis window\'s Lists tab.',
    ),
    examples: [
      'cmdSyntaxVerbs',
      'cmdSyntaxHistory',
    ],
    keywords: [
      'd',
      'p',
      'l',
      'verb',
      '命令',
      'command',
      'limit',
      '限定',
      '范围',
      'display',
      'stack',
      'BibleWorks',
    ],
  ),
  HelpTopic(
    id: 'scope',
    section: HelpSection.search,
    title: HelpText(
      '限定搜索范围',
      '限定搜尋範圍',
      'Limiting a search to part of the Bible',
    ),
    body: HelpText(
      '「搜索」›「检索范围…」可以选旧约、新约，或某几卷、某一段章。打勾表示目前有限制，状态栏也会显示。\n\n命令行的写法：l 创、l nt、l 太 5-7；单独打 l 取消。\n\n要按任意一组经节限定，在分析窗口的「经文列表」分页建一个列表，再把它设为搜索范围。限制会一直有效，直到你取消。',
      '「搜尋」›「檢索範圍…」可以選舊約、新約，或某幾卷、某一段章。打勾表示目前有限制，狀態列也會顯示。\n\n命令列的寫法：l 創、l nt、l 太 5-7；單獨打 l 取消。\n\n要按任意一組經節限定，在分析視窗的「經文列表」分頁建一個列表，再把它設為搜尋範圍。限制會一直有效，直到你取消。',
      'Search › Search scope… picks the Old or New Testament, some books, or a run of chapters. A tick means a limit is on, and the status bar says so too.\n\nOn the command line: l gen, l nt, l matt 5-7; l alone lifts it.\n\nTo limit to any set of verses, build a list on the Analysis window\'s Lists tab and use it as the scope. A limit stays on until you lift it.',
    ),
    path: ['search', 'scopeMenu'],
    keywords: [
      'scope',
      'limit',
      '范围',
      '限定',
      '旧约',
      '新约',
      'OT',
      'NT',
      'book',
      'range',
      '书卷',
      'filter',
      '过滤',
      'verse list',
      '经文列表',
    ],
    open: HelpDestination.searchScope,
  ),
  HelpTopic(
    id: 'cross-version',
    section: HelpSection.search,
    title: HelpText(
      '在几个译本里一起搜',
      '在幾個譯本里一起搜',
      'Searching several versions at once',
    ),
    body: HelpText(
      '「设置」里的「跨译本搜索」打开后，同一个文字查询会同时在几个同语言的译本里跑，并列出每个译本各命中几节——适合「记得有这句话，但不记得是哪个译本」。它只对文字搜索有效。\n\n想找「KJV 用这个词、CSB 用那个词」的经文，把译本写在词前面：.kjv:propitiation csb:atoning。',
      '「設定」裡的「跨譯本搜尋」開啟後，同一個文字查詢會同時在幾個同語言的譯本里跑，並列出每個譯本各命中幾節——適合「記得有這句話，但不記得是哪個譯本」。它只對文字搜尋有效。\n\n想找「KJV 用這個詞、CSB 用那個詞」的經文，把譯本寫在詞前面：.kjv:propitiation csb:atoning。',
      'Turn on Cross-version search in Settings and one text query runs across several editions of the same language, with a count per edition — for "I remember the wording but not which translation". Text searches only.\n\nTo find verses where the KJV says one thing and the CSB another, tag each word with its version: .kjv:propitiation csb:atoning.',
    ),
    path: ['menuFile', 'settings', 'crossVersionSearchMode'],
    examples: [
      'cmdSyntaxCrossVersion',
    ],
    keywords: [
      'cross version',
      '跨译本',
      'all versions',
      '所有译本',
      '多个译本',
      'multiple',
      'which translation',
      '哪个译本',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'search-options',
    section: HelpSection.search,
    title: HelpText(
      '希伯来文与希腊文的搜索选项',
      '希伯來文與希臘文的搜尋選項',
      'Hebrew and Greek search options',
    ),
    body: HelpText(
      '「设置」里还有三项：\n\n• 搜索时忽略希伯来元音点与希腊重音（默认开）：照着屏幕上看到的打就能找到，ברא 和 בָּרָא、θεος 和 θεός 互相匹配\n• 搜索时排除 Ketiv（所写的）\n• 搜索时排除 Qere（所读的）\n\n希伯来圣经有 1,103 节经文并列两种读法，后两项决定形态搜索和 NEAR / BEFORE 算哪一种。',
      '「設定」裡還有三項：\n\n• 搜尋時忽略希伯來元音點與希臘重音（預設開）：照著螢幕上看到的打就能找到，ברא 和 בָּרָא、θεος 和 θεός 互相匹配\n• 搜尋時排除 Ketiv（所寫的）\n• 搜尋時排除 Qere（所讀的）\n\n希伯來聖經有 1,103 節經文並列兩種讀法，後兩項決定形態搜尋和 NEAR / BEFORE 算哪一種。',
      'Three more in Settings:\n\n• Ignore Hebrew points and Greek accents (on by default): type what you see, and ברא finds בָּרָא, θεος finds θεός\n• Exclude Ketiv (as written)\n• Exclude Qere (as read)\n\nThe Hebrew Bible carries two readings in 1,103 verses; the last two decide which one morphology searches and NEAR / BEFORE count.',
    ),
    path: ['menuFile', 'settings'],
    keywords: [
      'pointing',
      '元音',
      '重音',
      'accent',
      'diacritics',
      'ketiv',
      'qere',
      '写法',
      '读法',
      'Hebrew',
      'Greek',
      '希伯来',
      '希腊',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'results',
    section: HelpSection.search,
    title: HelpText(
      '看搜索结果',
      '看搜尋結果',
      'Reading the results',
    ),
    body: HelpText(
      '结果列在命令行下面。点一条，中间的经文就滚到那一节并选中它，分析窗口也跟着换。\n\n• 结果上方的统计条显示命中多少节、分布在哪些书卷。\n• 短语搜索结果很少时，如果改成「.」同节搜索会多出很多，这里会直接写出多几节，并给一个一键改写——它只会提议实际跑过、确实更多的查询。\n• 「搜索」›「清除结果」清空列表。',
      '結果列在命令列下面。點一條，中間的經文就滾到那一節並選中它，分析視窗也跟著換。\n\n• 結果上方的統計條顯示命中多少節、分佈在哪些書卷。\n• 短語搜尋結果很少時，如果改成「.」同節搜尋會多出很多，這裡會直接寫出多幾節，並給一個一鍵改寫——它只會提議實際跑過、確實更多的查詢。\n• 「搜尋」›「清除結果」清空列表。',
      'Results are listed under the command line. Tap one and the text scrolls to that verse and selects it; the Analysis window follows.\n\n• The strip above the results shows how many verses matched and in which books.\n• When a phrase search finds little and the "." same-verse search would find many more, it says how many more and offers the rewrite in one tap — it only ever offers a query it has actually run.\n• Search › Clear results empties the list.',
    ),
    path: ['search', 'menuClearResults'],
    keywords: [
      'results',
      '结果',
      'hits',
      '命中',
      '统计',
      'distribution',
      '分布',
      'clear',
      '清除',
      'broaden',
      '放宽',
      'count',
      '数量',
    ],
  ),
  HelpTopic(
    id: 'analysis-tabs',
    section: HelpSection.analysis,
    title: HelpText(
      '分析窗口的各个分页',
      '分析視窗的各個分頁',
      'The Analysis window\'s tabs',
    ),
    body: HelpText(
      '分析窗口讲的是你当前选中的经文，或锁定的原文词。分页从左到右：\n\n• 原文研读：词义、词形分析、词典\n• 互参：串珠经文\n• 统计：这个词在各卷出现几次\n• 上下文（KWIC）：每处出现排成一行、对齐在关键词上，可以按左边或右边的词排序，看出常见搭配\n• 相关经文\n• 经文列表：自己建的经文列表，也能当搜索范围\n• 短语：找相同的原文短语\n• 生词：本段的词汇\n• 词形：同一个词的各种形态；也能按词性、时态等特征做形态搜索\n• 主题：现代汇编的主题\n• 语境：本段、本章、本卷的词汇\n• 地名：这节提到的地方\n• 讲道：引用这节的讲道\n• 笔记：你对这节的笔记，自动保存，不用按保存\n• 汇总：其他各分页对这节各有多少内容，帮你决定打开哪个\n• 平行：福音书的平行经文并排\n\n分页上的小圆点表示那一页对当前经文有内容。栏窄时分页只显示图标；点分析窗口标题栏上的标签按钮可以一直显示名称。',
      '分析視窗講的是你當前選中的經文，或鎖定的原文詞。分頁從左到右：\n\n• 原文研讀：詞義、詞形分析、詞典\n• 互參：串珠經文\n• 統計：這個詞在各卷出現幾次\n• 上下文（KWIC）：每處出現排成一行、對齊在關鍵詞上，可以按左邊或右邊的詞排序，看出常見搭配\n• 相關經文\n• 經文列表：自己建的經文列表，也能當搜尋範圍\n• 短語：找相同的原文短語\n• 生詞：本段的詞彙\n• 詞形：同一個詞的各種形態；也能按詞性、時態等特徵做形態搜尋\n• 主題：現代彙編的主題\n• 語境：本段、本章、本卷的詞彙\n• 地名：這節提到的地方\n• 講道：引用這節的講道\n• 筆記：你對這節的筆記，自動儲存，不用按儲存\n• 匯總：其他各分頁對這節各有多少內容，幫你決定開啟哪個\n• 平行：福音書的平行經文並排\n\n分頁上的小圓點表示那一頁對當前經文有內容。欄窄時分頁只顯示圖示；點分析視窗標題欄上的標籤按鈕可以一直顯示名稱。',
      'The Analysis window describes the verse you selected or the word you pinned. The tabs, left to right:\n\n• Word Study: meaning, parsing, lexicon\n• X-Refs: cross-references\n• Stats: how often the word occurs, book by book\n• KWIC: every occurrence on one line, aligned on the keyword, sortable by the words to its left or right to show what it goes with\n• Related verses\n• Lists: your own verse lists, which can also serve as a search scope\n• Phrases: the same original-language phrase elsewhere\n• Vocab: the vocabulary of the passage\n• Forms: every form of the word; also a morphology search by part of speech, tense and so on\n• Topics: the Modern Concordance\'s topics\n• Context: the vocabulary of the pericope, chapter and book\n• Places: places the verse mentions\n• Sermons: sermons that cite the verse\n• Notes: your notes on the verse, saved as you type\n• Summary: how much each other tab has on this verse, so you know which to open\n• Parallels: gospel parallels side by side\n\nA dot on a tab means it has something for this verse. In a narrow pane the tabs show icons only; the label button in the Analysis window\'s title bar keeps the names showing.',
    ),
    path: ['menuView', 'menuAnalysisWindow'],
    keywords: [
      'analysis',
      '分析',
      'tabs',
      '分页',
      'word study',
      '原文研读',
      'KWIC',
      '上下文',
      'cross references',
      '互参',
      '串珠',
      'morphology',
      '形态',
      '词形',
      'parsing',
      '词性',
      'notes',
      '笔记',
      'places',
      '地名',
      'synopsis',
      '平行',
      'topics',
      '主题',
      'vocabulary',
      '生词',
      'summary',
      '汇总',
      'phrases',
      '短语',
      'statistics',
      '统计',
      'verse list',
      '经文列表',
      'sermons',
      '讲道',
    ],
  ),
  HelpTopic(
    id: 'word-list',
    section: HelpSection.tools,
    title: HelpText(
      '词汇表',
      '詞彙表',
      'Word List',
    ),
    body: HelpText(
      '本章每一个原文词：编号、原形、词义和出现次数。想按原文编号搜索时，编号就从这里拿。',
      '本章每一個原文詞：編號、原形、詞義和出現次數。想按原文編號搜尋時，編號就從這裡拿。',
      'Every original-language word in the chapter: number, lemma, gloss and count. This is where to get a Strong\'s number to search with.',
    ),
    path: ['menuTools', 'wordListTitle'],
    keywords: [
      'word list',
      '词表',
      '词汇',
      'vocabulary',
      'lemma',
      'Strong',
      '编号',
      '原文',
    ],
    open: HelpDestination.wordList,
  ),
  HelpTopic(
    id: 'phrasing',
    section: HelpSection.tools,
    title: HelpText(
      '语法分行',
      '語法分行',
      'Phrasing',
    ),
    body: HelpText(
      '把当前经节按语法结构分行缩排，主句、从句一目了然。排好后可以复制。',
      '把當前經節按語法結構分行縮排，主句、從句一目瞭然。排好後可以複製。',
      'Lays the current verse out line by line by its grammar, so main and subordinate clauses stand apart. The result can be copied.',
    ),
    path: ['menuTools', 'phrasingTitle'],
    keywords: [
      'phrasing',
      '分行',
      '句式',
      '结构',
      'structure',
      'clause',
      '从句',
      'diagram',
      '语法',
    ],
    open: HelpDestination.phrasing,
  ),
  HelpTopic(
    id: 'passage-report',
    section: HelpSection.tools,
    title: HelpText(
      '经文研读报告',
      '經文研讀報告',
      'Passage report',
    ),
    body: HelpText(
      '为本章生成一份研读笔记。五个开关决定包含哪些内容，下面有预览——先看清长度和内容再复制，粘贴到任何文档里。\n\n快捷键 F4。',
      '為本章生成一份研讀筆記。五個開關決定包含哪些內容，下面有預覽——先看清長度和內容再複製，貼上到任何文件裡。\n\n快捷鍵 F4。',
      'Builds study notes for the chapter. Five switches decide what goes in, with a preview below — see what you are taking before you copy it into any document.\n\nShortcut: F4.',
    ),
    path: ['menuTools', 'reportTitle'],
    keywords: [
      'report',
      '报告',
      '笔记',
      'study notes',
      'export',
      '导出',
      'F4',
      'BibleWorks',
    ],
    open: HelpDestination.passageReport,
  ),
  HelpTopic(
    id: 'copy-center',
    section: HelpSection.tools,
    title: HelpText(
      '复制中心',
      '複製中心',
      'Copy Center',
    ),
    body: HelpText(
      '「文件」›「复制…」，或 Ctrl+Shift+C（Mac 上是 ⌘⇧C）。\n\n先选范围：选中的经文、当前经节、本章，或搜索结果；再选格式，然后复制。菜单项是灰的，表示现在没有可复制的东西。\n\n普通的 Ctrl+C / ⌘C 不变，仍然复制你用鼠标选中的文字。',
      '「檔案」›「複製…」，或 Ctrl+Shift+C（Mac 上是 ⌘⇧C）。\n\n先選範圍：選中的經文、當前經節、本章，或搜尋結果；再選格式，然後複製。選單項是灰的，表示現在沒有可複製的東西。\n\n普通的 Ctrl+C / ⌘C 不變，仍然複製你用滑鼠選中的文字。',
      'File › Copy…, or Ctrl+Shift+C (⌘⇧C on a Mac).\n\nPick the scope — selected verses, the current verse, this chapter, or the search results — then the format, and copy. A greyed menu item means there is nothing to copy yet.\n\nPlain Ctrl+C / ⌘C is untouched and still copies text you selected with the mouse.',
    ),
    path: ['menuFile', 'copyCenterMenu'],
    keywords: [
      'copy',
      '复制',
      'export',
      '导出',
      'clipboard',
      '剪贴板',
      'format',
      '格式',
      'results',
      'Ctrl+Shift+C',
    ],
    open: HelpDestination.copyCenter,
  ),
  HelpTopic(
    id: 'evidence',
    section: HelpSection.tools,
    title: HelpText(
      '圣经实证',
      '聖經實證',
      'Bible Evidence',
    ),
    body: HelpText(
      '考古、手抄本、历史与科学方面的发现，每一条都连到相关经文，可以浏览和搜索。',
      '考古、手抄本、歷史與科學方面的發現，每一條都連到相關經文，可以瀏覽和搜尋。',
      'Archaeological, manuscript, historical and scientific finds, each linked to the scripture it bears on; browse or search them.',
    ),
    path: ['menuTools', 'bibleEvidence'],
    keywords: [
      'evidence',
      '实证',
      '证据',
      'archaeology',
      '考古',
      'manuscript',
      '手抄本',
      'history',
      '历史',
    ],
    open: HelpDestination.evidence,
  ),
  HelpTopic(
    id: 'timeline',
    section: HelpSection.tools,
    title: HelpText(
      '时间线',
      '時間線',
      'Timeline',
    ),
    body: HelpText(
      '圣经事件按年代排成一条时间线。',
      '聖經事件按年代排成一條時間線。',
      'Biblical events laid out in order on a timeline.',
    ),
    path: ['menuTools', 'timeline'],
    keywords: [
      'timeline',
      '时间线',
      '年代',
      'history',
      'events',
      '事件',
    ],
    open: HelpDestination.timeline,
  ),
  HelpTopic(
    id: 'trivia',
    section: HelpSection.tools,
    title: HelpText(
      '圣经知识',
      '聖經知識',
      'Trivia',
    ),
    body: HelpText(
      '圣经里不容易注意到的结构和规律：离合诗、数字结构、神名的排列等等，按圣经顺序排列。',
      '聖經裡不容易注意到的結構和規律：離合詩、數字結構、神名的排列等等，按聖經順序排列。',
      'Patterns that are easy to miss: acrostics, numerical structures, the arrangement of divine names and more, in canonical order.',
    ),
    path: ['menuTools', 'trivia'],
    keywords: [
      'trivia',
      '知识',
      '冷知识',
      'acrostic',
      '离合诗',
      'pattern',
      '规律',
    ],
    open: HelpDestination.trivia,
  ),
  HelpTopic(
    id: 'sermons',
    section: HelpSection.resources,
    title: HelpText(
      '讲道',
      '講道',
      'Sermons',
    ),
    body: HelpText(
      '讲道文库，可以搜索；有音频的可以直接播放。\n\n想知道某节经文被哪些讲道引用：选中那节，看分析窗口的「讲道」分页。',
      '講道文庫，可以搜尋；有音訊的可以直接播放。\n\n想知道某節經文被哪些講道引用：選中那節，看分析視窗的「講道」分頁。',
      'The sermon library, searchable, with audio you can play where there is some.\n\nTo see which sermons cite a verse, select it and open the Analysis window\'s Sermons tab.',
    ),
    path: ['menuResources', 'sermons'],
    keywords: [
      'sermon',
      '讲道',
      '讲章',
      'preaching',
      'audio',
      '音频',
      '讲员',
      'speaker',
      '张恩年',
      'Eric Chang',
    ],
    open: HelpDestination.sermons,
  ),
  HelpTopic(
    id: 'atlas',
    section: HelpSection.resources,
    title: HelpText(
      '圣经地图集',
      '聖經地圖集',
      'Bible Atlas',
    ),
    body: HelpText(
      '圣经地名的地图。某节经文提到哪些地方，也可以在分析窗口的「地名」分页里看。',
      '聖經地名的地圖。某節經文提到哪些地方，也可以在分析視窗的「地名」分頁裡看。',
      'Maps of biblical places. For the places a particular verse mentions, see the Analysis window\'s Places tab.',
    ),
    path: ['menuResources', 'atlasTitle'],
    keywords: [
      'atlas',
      'map',
      '地图',
      '地名',
      'place',
      'geography',
      '地理',
    ],
    open: HelpDestination.atlas,
  ),
  HelpTopic(
    id: 'illustrations',
    section: HelpSection.resources,
    title: HelpText(
      '插图',
      '插畫',
      'Illustrations',
    ),
    body: HelpText(
      '一千多张圣经插图和图表，按卷浏览。打开一张后，← → 翻上一张、下一张，Esc 关闭。',
      '一千多張聖經插畫和圖表，按卷瀏覽。開啟一張後，← → 翻上一張、下一張，Esc 關閉。',
      'Over a thousand biblical plates and charts, by book. With one open, ← → step between them and Esc closes.',
    ),
    path: ['menuResources', 'maps'],
    keywords: [
      'illustration',
      '插图',
      '图片',
      'picture',
      'image',
      'plate',
      'chart',
      '图表',
    ],
    open: HelpDestination.illustrations,
  ),
  HelpTopic(
    id: 'naves',
    section: HelpSection.resources,
    title: HelpText(
      '内夫圣经主题辞典',
      '內夫聖經主題辭典',
      'Nave\'s Topical Bible',
    ),
    body: HelpText(
      '按主题查经文，例如「悔改」下面收了哪些经文。',
      '按主題查經文，例如「悔改」下面收了哪些經文。',
      'Look up scripture by topic — everything Nave filed under REPENTANCE, for example.',
    ),
    path: ['menuResources', 'navesTitle'],
    keywords: [
      'nave',
      '内夫',
      'topical',
      '主题',
      'topic',
      '辞典',
      'index',
    ],
    open: HelpDestination.naves,
  ),
  HelpTopic(
    id: 'modern-concordance',
    section: HelpSection.resources,
    title: HelpText(
      '现代汇编（新约）',
      '現代彙編（新約）',
      'Modern Concordance (NT)',
    ),
    body: HelpText(
      '新约的 341 个主题，每个主题下列出相关的希腊文词和经文。选中经节时，分析窗口的「主题」分页显示它属于哪些主题。',
      '新約的 341 個主題，每個主題下列出相關的希臘文詞和經文。選中經節時，分析視窗的「主題」分頁顯示它屬於哪些主題。',
      'The New Testament\'s 341 topics, each with its Greek words and verses. With a verse selected, the Analysis window\'s Topics tab shows which topics it falls under.',
    ),
    path: ['menuResources', 'modernConcordanceTitle'],
    keywords: [
      'concordance',
      '汇编',
      'topics',
      '主题',
      'Greek',
      '希腊文',
      'Eagle',
    ],
    open: HelpDestination.modernConcordance,
  ),
  HelpTopic(
    id: 'lexicon',
    section: HelpSection.resources,
    title: HelpText(
      '原文词典浏览',
      '原文詞典瀏覽',
      'Lexicon Browser',
    ),
    body: HelpText(
      '不用先找到经文，直接浏览和搜索希腊文、希伯来文词典：可以打原文、拉丁转写或编号，* 是通配符。',
      '不用先找到經文，直接瀏覽和搜尋希臘文、希伯來文詞典：可以打原文、拉丁轉寫或編號，* 是萬用字元。',
      'Browse and search the Greek and Hebrew lexicons without starting from a verse: type the word, a romanisation or a number, with * as a wildcard.',
    ),
    path: ['menuResources', 'lexiconBrowserTitle'],
    keywords: [
      'lexicon',
      '词典',
      '字典',
      'dictionary',
      'Greek',
      'Hebrew',
      '希腊',
      '希伯来',
      'Thayer',
      'BDB',
      'Strong',
    ],
    open: HelpDestination.lexicon,
  ),
  HelpTopic(
    id: 'family-tree',
    section: HelpSection.resources,
    title: HelpText(
      '圣经家谱',
      '聖經家譜',
      'Family Tree',
    ),
    body: HelpText(
      '圣经人物的家谱，点一个人看他的经文和亲属。',
      '聖經人物的家譜，點一個人看他的經文和親屬。',
      'The family tree of biblical people; tap a person for their passages and relations.',
    ),
    path: ['menuResources', 'familyTree'],
    keywords: [
      'family',
      '家谱',
      'genealogy',
      '人物',
      'people',
      'person',
      '族谱',
    ],
    open: HelpDestination.familyTree,
  ),
  HelpTopic(
    id: 'jesus-teachings',
    section: HelpSection.resources,
    title: HelpText(
      '主耶稣的教导',
      '主耶穌的教導',
      'The Teachings of the Lord Jesus',
    ),
    body: HelpText(
      '主耶稣亲口的教导，每条连到经文，并列出 app 里与它相关的其他内容。',
      '主耶穌親口的教導，每條連到經文，並列出 app 裡與它相關的其他內容。',
      'The Lord Jesus\' own teaching, each linked to the text and to what else the app has on it.',
    ),
    path: ['menuResources', 'jesusTeachingsTitle'],
    keywords: [
      'jesus',
      '耶稣',
      'teaching',
      '教导',
      '红字',
      'words of christ',
      '登山宝训',
    ],
    open: HelpDestination.jesusTeachings,
  ),
  HelpTopic(
    id: 'kings',
    section: HelpSection.resources,
    title: HelpText(
      '犹大与以色列列王',
      '猶大與以色列列王',
      'Kings of Judah & Israel',
    ),
    body: HelpText(
      '南北两国的君王排在同一条时间轴上（年代依 Thiele 的推算，页面上注明出处）。',
      '南北兩國的君王排在同一條時間軸上（年代依 Thiele 的推算，頁面上註明出處）。',
      'Both kingdoms\' kings on one time axis (dates follow Thiele\'s reconstruction, cited on the page).',
    ),
    path: ['menuResources', 'hebrewKings'],
    keywords: [
      'kings',
      '列王',
      '君王',
      'Judah',
      'Israel',
      '犹大',
      '以色列',
      'Thiele',
      'chronology',
    ],
    open: HelpDestination.hebrewKings,
  ),
  HelpTopic(
    id: 'chronology',
    section: HelpSection.resources,
    title: HelpText(
      '圣经年代（亚当到约瑟）',
      '聖經年代（亞當到約瑟）',
      'Bible Chronology',
    ),
    body: HelpText(
      '创世记 5 章和 11 章的寿数排成一条「创世纪年」时间轴，每个年龄都注明经文。',
      '創世記 5 章和 11 章的壽數排成一條「創世紀年」時間軸，每個年齡都註明經文。',
      'The lifespans of Genesis 5 and 11 on an Anno Mundi axis, each age cited to its verse.',
    ),
    path: ['menuResources', 'chronology'],
    keywords: [
      'chronology',
      '年代',
      '纪年',
      'Adam',
      '亚当',
      'Noah',
      '挪亚',
      'Genesis',
      '创世记',
      'lifespan',
      '寿数',
      'Anno Mundi',
    ],
    open: HelpDestination.chronology,
  ),
  HelpTopic(
    id: 'wheel',
    section: HelpSection.resources,
    title: HelpText(
      '世界史轮盘',
      '世界史輪盤',
      'World History Wheel',
    ),
    body: HelpText(
      '从公元前 4000 年到今天的世界历史画成一个圆盘：各国各朝代按时间排成一圈圈。',
      '從西元前 4000 年到今天的世界歷史畫成一個圓盤：各國各朝代按時間排成一圈圈。',
      'World history from 4000 BC to the present drawn as a wheel, the powers and dynasties in rings by date.',
    ),
    path: ['menuResources', 'wheelTitle'],
    keywords: [
      'wheel',
      '轮盘',
      'world history',
      '世界史',
      'history',
      '历史',
      'empires',
      '帝国',
      'dynasty',
      '朝代',
    ],
    open: HelpDestination.wheel,
  ),
  HelpTopic(
    id: 'strip',
    section: HelpSection.resources,
    title: HelpText(
      '世界史长条',
      '世界史長條',
      'World History Strip',
    ),
    body: HelpText(
      '同样的世界史，横着画成一条可以左右拖动的长条，适合细看某一段年代。',
      '同樣的世界史，橫著畫成一條可以左右拖動的長條，適合細看某一段年代。',
      'The same world history laid out as a long strip you drag sideways — better for looking closely at one stretch of time.',
    ),
    path: ['menuResources', 'stripPageTitle'],
    keywords: [
      'strip',
      '长条',
      'world history',
      '世界史',
      'timeline',
      'history',
      '历史',
    ],
    open: HelpDestination.strip,
  ),
  HelpTopic(
    id: 'projection',
    section: HelpSection.resources,
    title: HelpText(
      '投影',
      '投影',
      'Projection',
    ),
    body: HelpText(
      '把经文投到聚会的大屏幕上。从「资源」›「投影」进入，或在经文里选中几节后点「投影」。\n\n• 用方向键、空格、翻页笔操作；B 黑屏，+ / − 调字号，P 加上或去掉第二个译本\n• G 换一种深色背景，V 选第二个译本，R 调出存好的设置\n• A 打开聚会流程，[ ] 走上一项、下一项；C 倒计时\n• D 在第二个屏幕上打开投影窗口\n• Esc 离开\n\n完整的按键在「快捷键」一节。投影只用深色背景，字号和你平时读经的字号分开设定。',
      '把經文投到聚會的大螢幕上。從「資源」›「投影」進入，或在經文裡選中幾節後點「投影」。\n\n• 用方向鍵、空格、翻頁筆操作；B 黑屏，+ / − 調字號，P 加上或去掉第二個譯本\n• G 換一種深色背景，V 選第二個譯本，R 調出存好的設定\n• A 開啟聚會流程，[ ] 走上一項、下一項；C 倒計時\n• D 在第二個螢幕上開啟投影視窗\n• Esc 離開\n\n完整的按鍵在「快捷鍵」一節。投影只用深色背景，字號和你平時讀經的字號分開設定。',
      'Puts scripture on the screen at the front of a meeting. Open it from Resources › Projection, or select verses and choose Project.\n\n• Drive it with the arrows, Space or a presentation clicker; B blanks, + / − resize, P adds or drops a second version\n• G steps to the next dark background, V picks the second version, R recalls a saved setup\n• A opens the order of service and [ ] step through it; C is a countdown\n• D opens the projection window on a second screen\n• Esc leaves\n\nEvery key is listed under Keyboard shortcuts. Projection always uses a dark background, and its type size is separate from your reading size.',
    ),
    path: ['menuResources', 'projectionTitle'],
    keywords: [
      'projection',
      '投影',
      '投屏',
      'projector',
      '大屏幕',
      'screen',
      'church',
      '聚会',
      '教会',
      'service',
      '主日',
      'blank',
      '黑屏',
      'clicker',
      '翻页笔',
      'countdown',
      '倒计时',
      'agenda',
      '流程',
      'stage',
      '第二屏幕',
      'second screen',
      'presentation',
    ],
    notes: {
      HelpPlatform.web: HelpText(
        '按 D 会开一个新的浏览器窗口，把它拖到投影仪那个屏幕上并设为全屏；原来的窗口留在你面前操作。',
        '按 D 會開一個新的瀏覽器視窗，把它拖到投影儀那個螢幕上並設為全屏；原來的視窗留在你面前操作。',
        'D opens a new browser window: drag it to the projector\'s screen and make it full screen, and keep driving from the original.',
      ),
      HelpPlatform.macos: HelpText(
        '按 D 会在浏览器里打开投影窗口，把它拖到投影仪那个屏幕上并设为全屏。',
        '按 D 會在瀏覽器裡開啟投影視窗，把它拖到投影儀那個螢幕上並設為全屏。',
        'D opens the projection window in a browser: drag it to the projector\'s screen and make it full screen.',
      ),
      HelpPlatform.windows: HelpText(
        '按 D 会在浏览器里打开投影窗口，把它拖到投影仪那个屏幕上并设为全屏。',
        '按 D 會在瀏覽器裡開啟投影視窗，把它拖到投影儀那個螢幕上並設為全屏。',
        'D opens the projection window in a browser: drag it to the projector\'s screen and make it full screen.',
      ),
      HelpPlatform.linux: HelpText(
        '按 D 会在浏览器里打开投影窗口，把它拖到投影仪那个屏幕上并设为全屏。',
        '按 D 會在瀏覽器裡開啟投影視窗，把它拖到投影儀那個螢幕上並設為全屏。',
        'D opens the projection window in a browser: drag it to the projector\'s screen and make it full screen.',
      ),
      HelpPlatform.ios: HelpText(
        'iPad 没有第二个投影窗口（D 不起作用）。用系统的屏幕镜像把整个 iPad 画面投出去即可；外接键盘时上面的按键都能用。',
        'iPad 沒有第二個投影視窗（D 不起作用）。用系統的螢幕鏡像把整個 iPad 畫面投出去即可；外接鍵盤時上面的按鍵都能用。',
        'The iPad has no second projection window (D does nothing). Mirror the whole screen with the system\'s screen mirroring; with a keyboard attached, every key above works.',
      ),
      HelpPlatform.android: HelpText(
        'Android 平板没有第二个投影窗口（D 不起作用）。用系统的投屏把整个画面投出去即可。',
        'Android 平板沒有第二個投影視窗（D 不起作用）。用系統的投屏把整個畫面投出去即可。',
        'Android tablets have no second projection window (D does nothing). Cast the whole screen with the system\'s screen casting.',
      ),
    },
    open: HelpDestination.projection,
  ),
  HelpTopic(
    id: 'library',
    section: HelpSection.personal,
    title: HelpText(
      '笔记、高亮和书签',
      '筆記、高亮和書籤',
      'Notes, highlights and bookmarks',
    ),
    body: HelpText(
      '在经典阅读模式里选中经节后，可以加笔记、书签和高亮。\n\n• 「资源」›「我的收藏」把它们集中在一处，可以按经文顺序查看、跳回原处。\n• 某节经文的笔记也可以直接在分析窗口的「笔记」分页里写，边打边自动保存。',
      '在經典閱讀模式裡選中經節後，可以加筆記、書籤和高亮。\n\n• 「資源」›「我的收藏」把它們集中在一處，可以按經文順序檢視、跳回原處。\n• 某節經文的筆記也可以直接在分析視窗的「筆記」分頁裡寫，邊打邊自動儲存。',
      'Select verses in Classic Reader to add a note, a bookmark or a highlight.\n\n• Resources › Library gathers them in one place, in scripture order, one tap from where they belong.\n• A verse\'s note can also be written straight into the Analysis window\'s Notes tab, which saves as you type.',
    ),
    path: ['menuResources', 'library'],
    keywords: [
      'notes',
      '笔记',
      'highlights',
      '高亮',
      '划线',
      'bookmark',
      '书签',
      'library',
      '收藏',
      'favourites',
      '收藏夹',
      'annotation',
      '批注',
    ],
    open: HelpDestination.library,
  ),
  HelpTopic(
    id: 'your-data',
    section: HelpSection.personal,
    title: HelpText(
      '数据存在哪里，怎么换设备',
      '資料存在哪裡，怎麼換裝置',
      'Where your data lives, and moving devices',
    ),
    body: HelpText(
      '高亮、笔记、书签只保存在这台设备上，不上传，也没有云同步。\n\n换设备或重装前，在「设置」里用「导出我的数据」存一个文件（JSON 是完整备份；Markdown 可以直接贴进 Notion、Obsidian、备忘录），到新设备上用「导入」读回来。',
      '高亮、筆記、書籤只儲存在這臺裝置上，不上傳，也沒有云同步。\n\n換裝置或重新安裝前，在「設定」裡用「匯出我的資料」存一個檔案（JSON 是完整備份；Markdown 可以直接貼進 Notion、Obsidian、備忘錄），到新裝置上用「匯入」讀回來。',
      'Highlights, notes and bookmarks are stored on this device only — nothing is uploaded and there is no cloud sync.\n\nBefore changing devices or reinstalling, use Export my data in Settings to save a file (JSON is the complete backup; Markdown pastes into Notion, Obsidian or Notes), and Import it on the new device.',
    ),
    path: ['menuFile', 'settings'],
    keywords: [
      'export',
      '导出',
      'import',
      '导入',
      'backup',
      '备份',
      'sync',
      '同步',
      'cloud',
      '云',
      'data',
      '数据',
      '换设备',
      'new device',
      'transfer',
      '迁移',
      'privacy',
      '隐私',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'import-version',
    section: HelpSection.personal,
    title: HelpText(
      '导入你自己的圣经文本',
      '匯入你自己的聖經文本',
      'Importing your own Bible',
    ),
    body: HelpText(
      '「设置」›「导入你自己的圣经文本」：选一个 JSON 格式的经文文件，它就作为一个译本出现在版本列表里。这个文件只存在本机，不上传、不同步、不分享。',
      '「設定」›「匯入你自己的聖經文本」：選一個 JSON 格式的經文檔案，它就作為一個譯本出現在版本列表裡。這個檔案只存在本機，不上傳、不同步、不分享。',
      'Settings › Import your own Bible: choose a JSON scripture file and it appears as a version in the list. It stays on this device — never uploaded, synced or shared.',
    ),
    path: ['menuFile', 'settings', 'importVersionTitle'],
    keywords: [
      'import',
      '导入',
      'bible',
      'version',
      '译本',
      'JSON',
      'custom',
      '自己的',
      'text',
      '文本',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'settings',
    section: HelpSection.settings,
    title: HelpText(
      '设置里有什么',
      '設定裡有什麼',
      'What\'s in Settings',
    ),
    body: HelpText(
      '「文件」›「设置」，Mac 上也可以按 ⌘,（先点一下经文区）。\n\n• 显示：字号、菜单大小、行距、复制格式、字体、主题色\n• 阅读：浅色/深色/跟随系统、阅读模式、护眼纸质、粗体经文、段落标题、书卷简介、原文编号标记、导入你自己的圣经文本，以及跨译本搜索、忽略元音与重音、Ketiv / Qere 这几项搜索选项\n• 应用：界面语言、自动检查更新\n• 通知\n• 关于：导出和导入数据、离线包、清除缓存、重新查看导览、恢复设置',
      '「檔案」›「設定」，Mac 上也可以按 ⌘,（先點一下經文區）。\n\n• 顯示：字號、選單大小、行距、複製格式、字體、主題色\n• 閱讀：淺色/深色/跟隨系統、閱讀模式、護眼紙質、粗體經文、段落標題、書卷簡介、原文編號標記、匯入你自己的聖經文本，以及跨譯本搜尋、忽略元音與重音、Ketiv / Qere 這幾項搜尋選項\n• 應用：介面語言、自動檢查更新\n• 通知\n• 關於：匯出和匯入資料、離線包、清除快取、重新查看導覽、恢復設定',
      'File › Settings; on a Mac also ⌘, (click in the text first).\n\n• Display: text size, menu size, line spacing, copy format, font, theme colour\n• Reading: light/dark/system, reading mode, paper tone, bold text, section titles, book introductions, Strong\'s markers, importing your own Bible, and the search options — cross-version search, ignoring points and accents, Ketiv / Qere\n• App: interface language, automatic update checks\n• Notifications\n• About: export and import your data, the offline pack, clear cache, show the tour again, reset',
    ),
    path: ['menuFile', 'settings'],
    keywords: [
      'settings',
      '设置',
      'preferences',
      '偏好',
      'options',
      '选项',
      'config',
      '配置',
      '⌘,',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'language',
    section: HelpSection.settings,
    title: HelpText(
      '切换界面语言',
      '切換介面語言',
      'Changing the interface language',
    ),
    body: HelpText(
      '简体中文、繁體中文、English 三种。「设置」›「界面语言」，或者点各页面右上角的语言按钮。切换界面语言不会改变经文译本。',
      '簡體中文、繁體中文、English 三種。「設定」›「介面語言」，或者點各頁面右上角的語言按鈕。切換介面語言不會改變經文譯本。',
      'Simplified Chinese, Traditional Chinese or English: Settings › Interface Language, or the language button at the top right of each page. It does not change the Bible version.',
    ),
    path: ['menuFile', 'settings', 'interfaceLanguage'],
    keywords: [
      'language',
      '语言',
      '中文',
      '英文',
      'English',
      'Chinese',
      '简体',
      '繁体',
      'traditional',
      'simplified',
      'locale',
      'interface',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'updates',
    section: HelpSection.settings,
    title: HelpText(
      '更新到新版本',
      '更新到新版本',
      'Getting the new version',
    ),
    body: HelpText(
      '有新版本时，工具栏下面会出现一条提示。也可以随时用「帮助」›「检查更新」；「设置」里能开关自动检查、调检查频率。',
      '有新版本時，工具欄下面會出現一條提示。也可以隨時用「幫助」›「檢查更新」；「設定」裡能開關自動檢查、調檢查頻率。',
      'When a newer build exists, a banner appears under the toolbar. Help › Check for updates asks at any time; Settings turns the automatic check on or off and sets how often.',
    ),
    path: ['menuHelp', 'checkForUpdates'],
    keywords: [
      'update',
      '更新',
      'upgrade',
      '升级',
      'new version',
      '新版本',
      'version',
      '版本号',
      'download',
      '下载',
      'install',
      '安装',
    ],
    notes: {
      HelpPlatform.web: HelpText(
        '网页版不用手动更新，打开时就是最新版。如果看起来还是旧的，用「设置」›「清除缓存并重新加载」。',
        '網頁版不用手動更新，開啟時就是最新版。如果看起來還是舊的，用「設定」›「清除快取並重新載入」。',
        'The web version needs no updating — it is the latest whenever you open it. If it still looks old, use Settings › Clear cache & reload.',
      ),
      HelpPlatform.android: HelpText(
        'Android 上可以在 app 里直接下载并安装新版本（第一次需要允许「安装未知应用」）。',
        'Android 上可以在 app 裡直接下載並安裝新版本（第一次需要允許「安裝未知應用」）。',
        'On Android the update downloads and installs from inside the app (the first time, allow "install unknown apps").',
      ),
      HelpPlatform.macos: HelpText(
        '会打开下载页。下载新的 macOS 压缩包，解压后替换「应用程序」里原来的 Yahwehs-Sword.app。你的笔记和设置不会丢失。',
        '會開啟下載頁。下載新的 macOS 壓縮包，解壓後替換「應用程式」裡原來的 Yahwehs-Sword.app。你的筆記和設定不會丟失。',
        'Opens the download page. Download the new macOS zip, unzip it and replace Yahwehs-Sword.app in Applications. Your notes and settings are kept.',
      ),
      HelpPlatform.windows: HelpText(
        '会打开下载页。下载新的 Windows 压缩包，解压后覆盖原来的 Yahwehs-Sword 文件夹。你的笔记和设置不会丢失。',
        '會開啟下載頁。下載新的 Windows 壓縮包，解壓後覆蓋原來的 Yahwehs-Sword 資料夾。你的筆記和設定不會丟失。',
        'Opens the download page. Download the new Windows zip and unzip it over the old Yahwehs-Sword folder. Your notes and settings are kept.',
      ),
      HelpPlatform.linux: HelpText(
        '会打开下载页。下载新的 Linux 压缩包，解压后替换原来的文件夹。',
        '會開啟下載頁。下載新的 Linux 壓縮包，解壓後替換原來的資料夾。',
        'Opens the download page. Download the new Linux archive and unpack it over the old folder.',
      ),
      HelpPlatform.ios: HelpText(
        'iPad 版由开发者安装，检查更新会告诉你是否有新版本。',
        'iPad 版由開發者安裝，檢查更新會告訴你是否有新版本。',
        'The iPad build is installed by the developer; checking tells you whether a newer one exists.',
      ),
    },
    open: HelpDestination.checkForUpdates,
  ),
  HelpTopic(
    id: 'offline',
    section: HelpSection.settings,
    title: HelpText(
      '离线使用',
      '離線使用',
      'Using it offline',
    ),
    body: HelpText(
      '「设置」›「离线包」：勾选要下载的类别（圣经、讲道、工具、原文、地图），下载一次之后，没有网络也能用。',
      '「設定」›「離線包」：勾選要下載的類別（聖經、講道、工具、原文、地圖），下載一次之後，沒有網路也能用。',
      'Settings › Offline pack: tick the categories to download (Bibles, sermons, tools, originals, maps); after one download they work without a connection.',
    ),
    path: ['menuFile', 'settings', 'offlinePackTitle'],
    keywords: [
      'offline',
      '离线',
      '没网',
      'no internet',
      'network',
      '网络',
      'download',
      '下载',
      'cache',
      '缓存',
    ],
    only: {HelpPlatform.web},
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'install',
    section: HelpSection.settings,
    title: HelpText(
      '把网页版装到桌面或主屏幕',
      '把網頁版裝到桌面或主螢幕',
      'Installing the web version',
    ),
    body: HelpText(
      '网页版可以像 app 一样装到电脑桌面或平板主屏幕，打开时没有浏览器地址栏。\n\n• Chrome、Edge：「设置」里会出现「安装」按钮，或点地址栏右边的安装图标\n• iPad 上的 Safari：点「分享」›「添加到主屏幕」',
      '網頁版可以像 app 一樣裝到電腦桌面或平板主螢幕，開啟時沒有瀏覽器網址列。\n\n• Chrome、Edge：「設定」裡會出現「安裝」按鈕，或點網址列右邊的安裝圖示\n• iPad 上的 Safari：點「分享」›「加入主畫面」',
      'The web version installs like an app on a computer or a tablet home screen, and opens without the browser\'s address bar.\n\n• Chrome, Edge: an Install button appears in Settings, or use the install icon at the right of the address bar\n• Safari on iPad: Share › Add to Home Screen',
    ),
    path: ['menuFile', 'settings'],
    keywords: [
      'install',
      '安装',
      'PWA',
      'home screen',
      '主屏幕',
      '桌面',
      'desktop',
      'app',
      'shortcut',
      '添加到主屏幕',
    ],
    only: {HelpPlatform.web},
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'notifications',
    section: HelpSection.settings,
    title: HelpText(
      '通知',
      '通知',
      'Notifications',
    ),
    body: HelpText(
      '「设置」›「启用通知」。第一次打开时系统会问你是否允许；下面的「发送测试通知」可以马上发一条，看看能不能收到。',
      '「設定」›「啟用通知」。第一次開啟時系統會問你是否允許；下面的「發送測試通知」可以馬上發一條，看看能不能收到。',
      'Settings › Enable notifications. The system asks for permission the first time; Send test notification sends one straight away so you can check it arrives.',
    ),
    path: ['menuFile', 'settings', 'notificationsToggle'],
    keywords: [
      'notification',
      '通知',
      '提醒',
      'reminder',
      'alert',
      'push',
      '推送',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'reset',
    section: HelpSection.settings,
    title: HelpText(
      '出问题时：清除缓存、恢复设置、重看导览',
      '出問題時：清除快取、恢復設定、重看導覽',
      'When something is wrong: clear cache, reset, tour',
    ),
    body: HelpText(
      '都在「设置」最下面：\n\n• 清除缓存并重新加载：内容显示不对或像是旧版本时先试这个，你的笔记和高亮不受影响\n• 恢复设置：把外观和阅读选项改回默认\n• 重新查看导览：再看一遍第一次打开时的介绍\n\n仍然不行，请在「帮助」›「关于与数据来源」里找联系方式。',
      '都在「設定」最下面：\n\n• 清除快取並重新載入：內容顯示不對或像是舊版本時先試這個，你的筆記和高亮不受影響\n• 恢復設定：把外觀和閱讀選項改回預設\n• 重新查看導覽：再看一遍第一次開啟時的介紹\n\n仍然不行，請在「幫助」›「關於與資料來源」裡找聯絡方式。',
      'All at the bottom of Settings:\n\n• Clear cache & reload: try this first when something looks wrong or out of date — your notes and highlights are untouched\n• Reset settings: appearance and reading options back to their defaults\n• Show tour again: the first-run introduction once more\n\nStill stuck? Help › About & data sources has the contact details.',
    ),
    path: ['menuFile', 'settings'],
    keywords: [
      'problem',
      '问题',
      'bug',
      '错误',
      'error',
      '卡住',
      'stuck',
      'reset',
      '恢复',
      '重置',
      'cache',
      '缓存',
      'reload',
      '刷新',
      'tour',
      '导览',
      'onboarding',
      '联系',
      'contact',
      'feedback',
      '反馈',
    ],
    open: HelpDestination.settings,
  ),
  HelpTopic(
    id: 'about',
    section: HelpSection.settings,
    title: HelpText(
      '关于与数据来源',
      '關於與資料來源',
      'About & data sources',
    ),
    body: HelpText(
      '每个译本、词典和资料的出处与授权，以及版本号和联系方式。',
      '每個譯本、詞典和資料的出處與授權，以及版本號和聯絡方式。',
      'Where every version, lexicon and resource comes from and under what licence, plus the version number and contact details.',
    ),
    path: ['menuHelp', 'about'],
    keywords: [
      'about',
      '关于',
      'license',
      'licence',
      '授权',
      '版权',
      'copyright',
      'source',
      '来源',
      'version',
      '版本号',
      'contact',
      '联系',
    ],
    open: HelpDestination.about,
  ),
  HelpTopic(
    id: 'platform-web',
    section: HelpSection.platforms,
    title: HelpText(
      '在浏览器里用',
      '在瀏覽器裡用',
      'In a browser',
    ),
    body: HelpText(
      '打开 sword.yahwehword.com 就能用，不用安装，也总是最新版。\n\n• 浏览器自己占用的键（Ctrl/⌘+C、F、L、R、T、W 和 F3、F5、F11、F12 等）一律不抢，所以快捷键选的是 F1、F2、F4 和 Ctrl/⌘+Shift+C。\n• 可以装成桌面 app（见「把网页版装到桌面或主屏幕」），也可以下载离线包。\n• 投影可以开第二个窗口放到投影屏幕上。',
      '開啟 sword.yahwehword.com 就能用，不用安裝，也總是最新版。\n\n• 瀏覽器自己佔用的鍵（Ctrl/⌘+C、F、L、R、T、W 和 F3、F5、F11、F12 等）一律不搶，所以快捷鍵選的是 F1、F2、F4 和 Ctrl/⌘+Shift+C。\n• 可以裝成桌面 app（見「把網頁版裝到桌面或主螢幕」），也可以下載離線包。\n• 投影可以開第二個視窗放到投影螢幕上。',
      'Open sword.yahwehword.com — nothing to install, and always the latest version.\n\n• Keys the browser owns (Ctrl/⌘ with C, F, L, R, T, W, and F3, F5, F11, F12) are never taken, which is why the shortcuts are F1, F2, F4 and Ctrl/⌘+Shift+C.\n• It installs like a desktop app (see "Installing the web version"), and the offline pack works here.\n• Projection can open a second window for the projector\'s screen.',
    ),
    keywords: [
      'web',
      '网页',
      'browser',
      '浏览器',
      'Chrome',
      'Safari',
      'Edge',
      'Firefox',
      'online',
      '在线',
    ],
    only: {HelpPlatform.web},
  ),
  HelpTopic(
    id: 'platform-ios',
    section: HelpSection.platforms,
    title: HelpText(
      '在 iPad 上',
      '在 iPad 上',
      'On an iPad',
    ),
    body: HelpText(
      '横着拿。没有鼠标就没有「指向」：点一下原文词就锁定并显示它，再点一次取消。经典阅读模式里左右滑动翻章。\n\n接上键盘（例如妙控键盘）后，这份说明里的快捷键都能用，⌘ 键就是 Command。投影没有第二窗口，用系统的屏幕镜像。',
      '橫著拿。沒有滑鼠就沒有「指向」：點一下原文詞就鎖定並顯示它，再點一次取消。經典閱讀模式裡左右滑動翻章。\n\n接上鍵盤（例如妙控鍵盤）後，這份說明裡的快捷鍵都能用，⌘ 鍵就是 Command。投影沒有第二視窗，用系統的螢幕鏡像。',
      'Hold it landscape. Without a mouse there is no pointing: tap an original-language word to pin and show it, tap again to release. In Classic Reader, swipe sideways to turn the chapter.\n\nWith a keyboard attached (a Magic Keyboard, say) every shortcut here works, ⌘ being Command. Projection has no second window; use the system\'s screen mirroring.',
    ),
    keywords: [
      'iPad',
      'iOS',
      'Apple',
      'touch',
      '触屏',
      'tablet',
      '平板',
      'keyboard',
      '键盘',
      'Magic Keyboard',
      '妙控',
    ],
    only: {HelpPlatform.ios},
  ),
  HelpTopic(
    id: 'platform-android',
    section: HelpSection.platforms,
    title: HelpText(
      '在 Android 平板上',
      '在 Android 平板上',
      'On an Android tablet',
    ),
    body: HelpText(
      '横着拿，宽度要到 992 像素（大多数 10 寸以上的平板可以）。点一下原文词锁定，再点一次取消；经典阅读模式里左右滑动翻章。\n\n更新可以在 app 里直接下载安装。接键盘后快捷键用 Ctrl。',
      '橫著拿，寬度要到 992 像素（大多數 10 寸以上的平板可以）。點一下原文詞鎖定，再點一次取消；經典閱讀模式裡左右滑動翻章。\n\n更新可以在 app 裡直接下載安裝。接鍵盤後快捷鍵用 Ctrl。',
      'Hold it landscape; it needs 992 pixels of width, which most 10-inch-plus tablets have. Tap an original-language word to pin it, tap again to release; in Classic Reader, swipe sideways to turn the chapter.\n\nUpdates download and install inside the app. With a keyboard, shortcuts use Ctrl.',
    ),
    keywords: [
      'Android',
      '安卓',
      'tablet',
      '平板',
      'touch',
      '触屏',
      'Samsung',
      '三星',
      'Xiaomi',
      '小米',
      'Pad',
      'APK',
    ],
    only: {HelpPlatform.android},
  ),
  HelpTopic(
    id: 'platform-macos',
    section: HelpSection.platforms,
    title: HelpText(
      '在 Mac 上',
      '在 Mac 上',
      'On a Mac',
    ),
    body: HelpText(
      '快捷键用 ⌘：⌘⇧C 复制中心，⌘[ ⌘] 上一章下一章，⌘, 设置；F1、F2、F4 在笔记本上可能要同时按 fn。\n\n第一次打开下载的 app 时，如果 macOS 说无法验证开发者：在「应用程序」里右键点 Yahwehs-Sword，选「打开」，再点一次「打开」。之后就正常了。',
      '快捷鍵用 ⌘：⌘⇧C 複製中心，⌘[ ⌘] 上一章下一章，⌘, 設定；F1、F2、F4 在筆記本上可能要同時按 fn。\n\n第一次開啟下載的 app 時，如果 macOS 說無法驗證開發者：在「應用程式」裡右鍵點 Yahwehs-Sword，選「開啟」，再點一次「開啟」。之後就正常了。',
      'Shortcuts use ⌘: ⌘⇧C Copy Center, ⌘[ ⌘] previous and next chapter, ⌘, Settings. On a laptop F1, F2 and F4 may need fn held down.\n\nIf macOS says it cannot verify the developer the first time you open the downloaded app: in Applications, right-click Yahwehs-Sword, choose Open, then Open again. It opens normally from then on.',
    ),
    keywords: [
      'Mac',
      'macOS',
      'Apple',
      'MacBook',
      '⌘',
      'Command',
      'fn',
      'Gatekeeper',
      '无法验证',
      'cannot be opened',
      'unidentified developer',
      '身份不明',
    ],
    only: {HelpPlatform.macos},
  ),
  HelpTopic(
    id: 'platform-windows',
    section: HelpSection.platforms,
    title: HelpText(
      '在 Windows 上',
      '在 Windows 上',
      'On Windows',
    ),
    body: HelpText(
      '解压下载的压缩包，运行 Yahwehs-Sword 文件夹里的 Yahwehs-Sword.exe。快捷键用 Ctrl：Ctrl+Shift+C 复制中心，Ctrl+[ Ctrl+] 上一章下一章。\n\n如果 Windows 弹出「Windows 已保护你的电脑」，点「更多信息」›「仍要运行」。',
      '解壓下載的壓縮包，執行 Yahwehs-Sword 資料夾裡的 Yahwehs-Sword.exe。快捷鍵用 Ctrl：Ctrl+Shift+C 複製中心，Ctrl+[ Ctrl+] 上一章下一章。\n\n如果 Windows 彈出「Windows 已保護你的電腦」，點「更多資訊」›「仍要執行」。',
      'Unzip the download and run Yahwehs-Sword.exe inside the Yahwehs-Sword folder. Shortcuts use Ctrl: Ctrl+Shift+C Copy Center, Ctrl+[ Ctrl+] previous and next chapter.\n\nIf Windows shows "Windows protected your PC", choose More info › Run anyway.',
    ),
    keywords: [
      'Windows',
      'PC',
      'exe',
      'Ctrl',
      'SmartScreen',
      '保护',
      'protected',
      '运行',
      'run anyway',
    ],
    only: {HelpPlatform.windows},
  ),
  HelpTopic(
    id: 'platform-linux',
    section: HelpSection.platforms,
    title: HelpText(
      '在 Linux 上',
      '在 Linux 上',
      'On Linux',
    ),
    body: HelpText(
      '解压下载的压缩包，在文件夹里运行 ./Yahwehs-Sword。快捷键用 Ctrl，和 Windows 相同。',
      '解壓下載的壓縮包，在資料夾裡執行 ./Yahwehs-Sword。快捷鍵用 Ctrl，和 Windows 相同。',
      'Unpack the download and run ./Yahwehs-Sword in its folder. Shortcuts use Ctrl, as on Windows.',
    ),
    keywords: [
      'Linux',
      'Ubuntu',
      'Debian',
      'Fedora',
      'Ctrl',
      'terminal',
      '终端',
    ],
    only: {HelpPlatform.linux},
  ),
];

/// Headings for the shortcut groups the Help page prints.
const Map<String, HelpText> kHelpKeyGroupTitles = {
  'keysWorkbench': HelpText(
    '整个工作台',
    '整個工作臺',
    'Anywhere in the workbench',
  ),
  'keysReader': HelpText(
    '经文区（先点一下经文）',
    '經文區（先點一下經文）',
    'In the text (click it first)',
  ),
  'keysCommandLine': HelpText(
    '命令行里',
    '命令列裡',
    'In the command line',
  ),
  'keysProjection': HelpText(
    '投影',
    '投影',
    'Projection',
  ),
  'keysPlateViewer': HelpText(
    '看插图时',
    '看插畫時',
    'Viewing an illustration',
  ),
  'keysPickers': HelpText(
    '检索范围、选择版本窗口',
    '檢索範圍、選擇版本視窗',
    'Search scope and version pickers',
  ),
  'keysTouch': HelpText(
    '触屏手势',
    '觸屏手勢',
    'Touch gestures',
  ),
};

/// What a finger does, for the touch platforms — (gesture, effect).
const List<(HelpText, HelpText)> kHelpTouchGestures = [
  (
    HelpText(
      '点一下原文词',
      '點一下原文詞',
      'Tap an original-language word',
    ),
    HelpText(
      '锁定并显示它；再点一次取消',
      '鎖定並顯示它；再點一次取消',
      'Pin and show it; tap again to release',
    ),
  ),
  (
    HelpText(
      '点一下经节（经典阅读模式）',
      '點一下經節（經典閱讀模式）',
      'Tap a verse (Classic Reader)',
    ),
    HelpText(
      '选中；可以连续点选多节',
      '選中；可以連續點選多節',
      'Select it; keep tapping for more',
    ),
  ),
  (
    HelpText(
      '左右滑动经文（经典阅读模式）',
      '左右滑動經文（經典閱讀模式）',
      'Swipe the text sideways (Classic Reader)',
    ),
    HelpText(
      '上一章 / 下一章',
      '上一章 / 下一章',
      'Previous / next chapter',
    ),
  ),
  (
    HelpText(
      '拖动栏之间的分隔条',
      '拖動欄之間的分隔條',
      'Drag the divider between panes',
    ),
    HelpText(
      '调整宽窄',
      '調整寬窄',
      'Resize the panes',
    ),
  ),
  (
    HelpText(
      '按住图标或按钮',
      '按住圖示或按鈕',
      'Long-press an icon or button',
    ),
    HelpText(
      '显示它的名称',
      '顯示它的名稱',
      'Show its name',
    ),
  ),
];
