/// Who preached the sermons — spelled once, in one place, for every
/// surface that shows them.
///
/// **Why this is a file and not three ui_strings entries.** The corpus
/// shipped for months with the preacher's name on no reading surface at
/// all: `sermonsTagline` ("Pastor Eric Chang's sermon library") was
/// defined and rendered nowhere, the library header said only "讲道", and
/// an individual sermon showed its id, date, passage and topic but never
/// its author. The only place a reader could meet the name was an
/// offline-download row buried in Settings — and that row spelled it
/// differently again. A name retyped per screen drifts per screen. Here
/// it is written three times total, once per locale, and every surface
/// composes from it.
///
/// **The shape comes from BibleWorks.** bwh10i is a *Version Info* tab in
/// the Analysis window: the credit for a resource follows whichever
/// resource has focus in the Browse window, and the copyright text lives
/// inside the version's own data file (`wtt.bww`) rather than in the
/// program's UI. Two things follow from that. Provenance belongs next to
/// the text, not only in an About dialog. And it belongs to the resource,
/// so it should have exactly one definition. `assets/sermons/index.json`
/// carries no author field — it is generated by
/// `scripts/ingest_sermons.py` from a source tree that had none — so this
/// file plays the part of the `.bww`, exactly as `sermon_topics.dart`
/// already holds the localised topic labels the corpus JSON also lacks.
///
/// **Weight.** One quiet line per surface, at attribution weight, never a
/// banner and never repeated down a list. Preaching credited on every row
/// of a 289-item list is advertising, not attribution.
library;

/// The preacher, as he is named in each locale.
///
/// "H.H." is not decoration — it is the form the corpus owner asked for
/// and the form that distinguishes him from other Chang. Do not shorten
/// it back to "Eric Chang"; `test/sermon_credit_test.dart` fails if any
/// second spelling appears anywhere in `uiStrings`.
const Map<String, String> _preacherByLocale = {
  'zh-Hans': '张熙和牧师',
  'zh-Hant': '張熙和牧師',
  'en': 'Pastor Eric H.H. Chang',
};

/// The preacher's name alone. This is the byline on an individual
/// sermon: under the title, above the metadata, the way a byline sits
/// under an article headline.
String preacherName(String locale) =>
    _preacherByLocale[locale] ?? _preacherByLocale['en']!;

/// Collection-level credit for the sermon library header.
///
/// Composed rather than stored so the name cannot drift away from
/// [preacherName]. Chinese puts the name first and the collective noun
/// last; English needs the preposition — which is the whole reason this
/// is a function and not a suffix constant.
String sermonLibraryCredit(String locale) {
  final name = preacherName(locale);
  switch (locale) {
    case 'zh-Hans':
      return '$name讲道集';
    case 'zh-Hant':
      return '$name講道集';
    default:
      return 'Sermons by $name';
  }
}

/// Substitute the preacher into any `uiStrings` value that carries the
/// `{name}` placeholder.
///
/// Settings' offline-pack row wants the name inside a longer sentence
/// that also states a file count. Storing the sentence in `uiStrings`
/// keeps it with the other Settings copy; storing `{name}` instead of the
/// name keeps this file the only place the name is written.
String withPreacher(String template, String locale) =>
    template.replaceAll('{name}', preacherName(locale));
