#!/usr/bin/env python3
"""Generate lib/utils/diacritics.dart — the precomposed→base fold table.

Dart has no String.normalize(): there is no NFD in the SDK and no
package in this app's dependency set that provides one. Search therefore
cannot decompose 'ό' into 'ο' + U+0301 at runtime and drop the mark, the
way every other platform would. What it CAN do is look a codepoint up in
a table, so this script bakes NFD's answer for the ranges the app's texts
actually use and emits it as a const map.

Ranges covered, and why each one is here:
  U+00C0–U+024F  Latin-1 Supplement + Latin Extended-A/B — Strong's
                 transliterations (agápē, bᵉrêʼshîyth) and the handful of
                 accented words in the English editions.
  U+1E00–U+1EFF  Latin Extended Additional — the underdot/macron letters
                 academic transliteration uses.
  U+0370–U+03FF  Greek and Coptic — precomposed monotonic accents.
  U+1F00–U+1FFF  Greek Extended — precomposed polytonic; this is what
                 assets/originals/*.json and assets/strongs/greek.json
                 are written in.

A codepoint is included only when NFD changes it AND the surviving base
is a LETTER. That excludes the standalone spacing diacritics (U+0385
GREEK DIALYTIKA TONOS decomposes to ¨ + U+0301, base category Sk) and the
punctuation lookalikes (U+037E GREEK QUESTION MARK → ';', U+0387 GREEK
ANO TELEIA → '·'), none of which are a letter wearing an accent and none
of which should turn into one.

Compatibility decomposition (NFKD) is NOT used. It would fold 'ﬁ' to
'fi' and '²' to '2', which is a different and much less defensible claim
than "this letter has an accent on it".

Run:  python3 scripts/build_diacritics_table.py
Then: git diff lib/utils/diacritics.dart   (should be empty if unchanged)
"""

import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "lib" / "utils" / "diacritics.dart"

RANGES = [
    (0x00C0, 0x024F, "Latin-1 Supplement + Latin Extended-A/B"),
    (0x0370, 0x03FF, "Greek and Coptic"),
    (0x1E00, 0x1EFF, "Latin Extended Additional"),
    (0x1F00, 0x1FFF, "Greek Extended"),
]


def base_of(cp: int):
    """The letter left when NFD's combining marks are dropped, or None."""
    ch = chr(cp)
    nfd = unicodedata.normalize("NFD", ch)
    if nfd == ch:
        return None
    stripped = "".join(c for c in nfd if not unicodedata.combining(c))
    if len(stripped) != 1:
        return None
    if not unicodedata.category(stripped).startswith("L"):
        return None
    if stripped == ch:
        return None
    return stripped


def main() -> None:
    pairs = []
    skipped = []
    for lo, hi, _label in RANGES:
        for cp in range(lo, hi + 1):
            try:
                unicodedata.name(chr(cp))
            except ValueError:
                continue
            b = base_of(cp)
            if b is None:
                if unicodedata.normalize("NFD", chr(cp)) != chr(cp):
                    skipped.append(cp)
                continue
            pairs.append((cp, ord(b)))

    by_range = {}
    for cp, b in pairs:
        for lo, hi, label in RANGES:
            if lo <= cp <= hi:
                by_range.setdefault(label, []).append((cp, b))
                break

    lines = []
    lines.append("// GENERATED by scripts/build_diacritics_table.py — do not hand-edit.")
    lines.append("// Re-run the script and commit the diff instead.")
    lines.append("//")
    lines.append("/// One-way diacritic folding for SEARCH COMPARISON ONLY.")
    lines.append("///")
    lines.append("/// 2026-08-16 (#321). A reader in Hong Kong searched the Greek text")
    lines.append("/// for `ὁ θεός` and got nothing. She had spelled it correctly. The")
    lines.append("/// app's only Greek edition (`lxxwh`) is set WITHOUT accents, while")
    lines.append("/// every Greek word the app SHOWS her — Word Study's parsed forms,")
    lines.append("/// the Strong's lexicon's lemmas — carries them. 19,555 distinct")
    lines.append("/// accented Greek forms are displayed by this app and, typed exactly")
    lines.append("/// as displayed, none of them could be found. Hebrew was half-fixed:")
    lines.append("/// the command grammar stripped points, but only when the QUERY")
    lines.append("/// already contained Hebrew letters, and the plain substring scan")
    lines.append("/// never stripped anything.")
    lines.append("///")
    lines.append("/// The fix is to compare like with like: fold both sides. The")
    lines.append("/// obligation that comes with it is that the fold must never be")
    lines.append("/// visible. Stored text is not touched, nothing rendered goes")
    lines.append("/// through here, and the clipboard does not either — an accent is")
    lines.append("/// part of the word, and a reader who copies `ἀγάπη` must get")
    lines.append("/// `ἀγάπη`. The fold exists in the comparison layer and dies there.")
    lines.append("///")
    lines.append("/// Folding is one-way and lossy on purpose: `ᾅ` and `ἁ` and `α` all")
    lines.append("/// become `α`, so a search can over-match. Over-matching shows the")
    lines.append("/// reader a verse they can check; under-matching tells them the word")
    lines.append("/// is not in the Bible, which was the bug.")
    lines.append("///")
    lines.append("/// Case is NOT folded here. Every caller lower-cases separately and")
    lines.append("/// `splitOnTerms` needs the original case to slice display text.")
    lines.append("library;")
    lines.append("")
    lines.append("/// Precomposed letter → the same letter without its marks.")
    lines.append("///")
    lines.append("/// Generated from Unicode NFD. A codepoint is here only when NFD")
    lines.append("/// changes it and the surviving base is a letter, which is why the")
    lines.append("/// standalone spacing diacritics (U+0385 ΅, U+1FCD ῍) and the")
    lines.append("/// punctuation lookalikes (U+037E ; U+0387 ·) are absent — none of")
    lines.append("/// them is a letter wearing an accent.")
    lines.append("const Map<int, int> kDiacriticBase = <int, int>{")
    for lo, hi, label in RANGES:
        items = by_range.get(label, [])
        if not items:
            continue
        lines.append("  // %s (U+%04X–U+%04X): %d." % (label, lo, hi, len(items)))
        row = []
        for cp, b in items:
            row.append("0x%04X: 0x%04X," % (cp, b))
            if len(row) == 4:
                lines.append("  " + " ".join(row))
                row = []
        if row:
            lines.append("  " + " ".join(row))
    lines.append("};")
    lines.append("")
    lines.append(BODY)

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s: %d pairs" % (OUT, len(pairs)))
    for lo, hi, label in RANGES:
        print("  %-44s %d" % (label, len(by_range.get(label, []))))
    print("  excluded (decomposes, base is not a letter): %d" % len(skipped))
    print("   ", " ".join("U+%04X" % c for c in skipped))


BODY = r'''
/// Combining marks that are dropped rather than mapped.
///
/// The Latin/Greek block is what NFD leaves behind, so text that arrives
/// already decomposed folds the same way as text that arrives
/// precomposed. The Hebrew set is listed codepoint by codepoint because
/// U+0591–U+05C7 is not uniformly marks: U+05BE MAQAF, U+05C0 PASEQ,
/// U+05C3 SOF PASUQ and U+05C6 NUN HAFUKHA are punctuation and stay.
bool isCombiningMark(int c) =>
    (c >= 0x0300 && c <= 0x036F) ||
    (c >= 0x0591 && c <= 0x05BD) ||
    c == 0x05BF ||
    c == 0x05C1 ||
    c == 0x05C2 ||
    c == 0x05C4 ||
    c == 0x05C5 ||
    c == 0x05C7;

/// Cheap rejection: everything this file can possibly change lives in
/// one of three spans. CJK, Cyrillic, ASCII and the astral planes all
/// fail it on the first or second comparison, which matters because the
/// corpus fold runs over every character of every verse in the edition.
bool _mayFold(int c) =>
    (c >= 0x00C0 && c <= 0x024F) ||
    (c >= 0x0300 && c <= 0x05C7) ||
    (c >= 0x1E00 && c <= 0x1FFF);

bool _foldable(int c) => _mayFold(c) && (isCombiningMark(c) || kDiacriticBase.containsKey(c));

/// Strip diacritics for comparison. Case is left alone.
///
/// Returns the argument itself when there is nothing to do, so the
/// English editions — which are the overwhelming majority of what this
/// runs on — pay one scan and no allocation.
String foldDiacritics(String s) {
  for (var i = 0; i < s.length; i++) {
    if (_foldable(s.codeUnitAt(i))) return _fold(s, i);
  }
  return s;
}

String _fold(String s, int from) {
  final buf = StringBuffer(s.substring(0, from));
  for (var i = from; i < s.length; i++) {
    final c = s.codeUnitAt(i);
    if (!_mayFold(c)) {
      buf.writeCharCode(c);
      continue;
    }
    if (isCombiningMark(c)) continue;
    buf.writeCharCode(kDiacriticBase[c] ?? c);
  }
  return buf.toString();
}

/// [foldDiacritics], plus where every surviving character came from.
///
/// Greek folds one-for-one, but Hebrew does not — dropping the points
/// off `בָּרָא` shortens it — so a match found in folded text cannot be
/// sliced out of the original by the same offsets. [sourceIndex] carries
/// them across: `sourceIndex[i]` is the index in the ORIGINAL string of
/// the character that produced `folded[i]`, and one extra entry at the
/// end holds the original's length, so a folded range `[i, j)` is the
/// original range `[sourceIndex[i], sourceIndex[j])`.
///
/// Marks land inside the span of the letter they sit on, which is what a
/// highlight should do with them anyway.
class FoldedText {
  const FoldedText(this.folded, this.sourceIndex);
  final String folded;
  final List<int> sourceIndex;
}

FoldedText foldDiacriticsAligned(String s) {
  final buf = StringBuffer();
  final idx = <int>[];
  for (var i = 0; i < s.length; i++) {
    final c = s.codeUnitAt(i);
    if (!_mayFold(c)) {
      buf.writeCharCode(c);
      idx.add(i);
      continue;
    }
    if (isCombiningMark(c)) continue;
    buf.writeCharCode(kDiacriticBase[c] ?? c);
    idx.add(i);
  }
  idx.add(s.length);
  return FoldedText(buf.toString(), idx);
}
'''


if __name__ == "__main__":
    main()
